import type { QuestionContent } from '../types'

// Seviye 1 (İlk Tanışma) havuzu — ilk parti, 24 soru.
// İçerik onayı: docs/product/QUESTIONS_LEVEL1.md (Aşama 3).
// Parti kısıtları: kategori başına ≤3, trait başına ≤2,
// 8 ikilem / 10 çoktan seçmeli / 6 slider.
export const level1Questions: QuestionContent[] = [
  // Tat & Mutfak
  {
    slug: 'hep-aldigim-sey',
    category: 'lezzet',
    subcategory: 'restoran ritüelleri',
    trait: 'merak-tarzi',
    level: 1,
    intensity: 1,
    type: 'either_or',
    estSeconds: 8,
    sparkScore: 4,
    funScore: 4,
    prompt:
      'Çok sevdiğin bir mekândasın. Menüde hiç denemediğin ama kulağa harika gelen bir şey var. Ne yaparsın?',
    options: [
      { id: 'klasik', label: 'Riske girmem — hep aldığımı alırım, zaten o yüzden seviyorum burayı' },
      { id: 'yeni', label: 'Yeni olan neyse o — en kötü senin tabağından alırım' },
    ],
    shuffleOptions: true,
    followupPrompt:
      'Birbirinize "değişmez siparişim" dediğiniz klasiği ve onu ilk keşfettiğiniz anı anlatın.',
    qualityNote:
      'Merak tarzını sıfatla değil sahneyle yoklar; iki cevap da savunulabilir. "Senin tabağından alırım" iki kişilik bağlama göz kırpar.',
    answerWeights: {
      klasik: { 'merak-tarzi': -1, 'konfor-alani': 1 },
      yeni: { 'merak-tarzi': 1, 'risk-istahi': 0.5 },
    },
    status: 'active',
  },
  {
    slug: 'gece-mutfagi',
    category: 'lezzet',
    subcategory: 'gece atıştırması',
    trait: 'ritual-bagliligi',
    level: 1,
    intensity: 1,
    type: 'choice',
    estSeconds: 10,
    sparkScore: 3,
    funScore: 5,
    prompt: 'Gece yarısı, herkes uyuyor, mutfağa süzüldün. Elinde büyük ihtimalle ne var?',
    options: [
      { id: 'dolap', label: 'Dolapta ne bulursam — soğuk soğuk, gerekirse tencereden' },
      { id: 'tatli', label: 'Tatlı bir şeyler; çikolata radarım gece de kapanmaz' },
      { id: 'sandvic', label: 'Ciddi iş: kendime düzgün bir sandviç kuruyorum' },
      { id: 'su', label: 'Ben sadece su almaya inmiştim, yemin ederim' },
    ],
    // Son seçenek espri olarak en sonda çalışır; sıra sabit kalır.
    shuffleOptions: false,
    followupPrompt:
      'Gece mutfağının en garip eserini itiraf etme turu: en tuhaf gece atıştırması hanginizde?',
    qualityNote:
      'Evrensel ve suçsuz bir küçük itiraf sahnesi; her seçenek mini bir karakter vinyeti, dördüncüsü kaçış değil espri.',
    answerWeights: {
      dolap: { 'spontanlik': 1 },
      tatli: { 'ritual-bagliligi': 0.5 },
      sandvic: { 'plan-sevgisi': 0.5 },
      su: {},
    },
    status: 'active',
  },
  {
    slug: 'catal-diplomasisi',
    category: 'lezzet',
    subcategory: 'masa kültürü',
    trait: 'paylasim-istahi',
    level: 1,
    intensity: 1,
    type: 'slider',
    estSeconds: 6,
    sparkScore: 4,
    funScore: 5,
    prompt: 'Masada yemek paylaşımı konusunda neredesin?',
    slider: {
      min: 1,
      max: 5,
      lowLabel: 'Tabağım kalemdir, sınırdır',
      highLabel: 'Masadaki her şey ortaktır, çatalım gezer',
    },
    shuffleOptions: false,
    followupPrompt:
      'Masada tabak paylaşımının kuralları ne olmalı? İkiniz bir "çatal anayasası" yazın.',
    qualityNote:
      'İki uç da pozitif ve sahiplenilebilir; gerçek bir spektrum. Buluşma masasında sorulunca o masayı sohbet konusu yapar.',
    answerWeights: {
      low: { 'paylasim-istahi': -1, 'alan-ihtiyaci': 1 },
      mid: {},
      high: { 'paylasim-istahi': 1 },
    },
    status: 'active',
  },
  // Seyahat & Keşif
  {
    slug: 'gece-yolculugu-teklifi',
    category: 'kesif',
    subcategory: 'spontane plan',
    trait: 'spontanlik',
    level: 1,
    intensity: 1,
    type: 'either_or',
    estSeconds: 8,
    sparkScore: 5,
    funScore: 4,
    prompt:
      'Arkadaşın gece 22.00’de aradı: "Hadi şimdi yola çıkalım, sabah deniz kenarındayız." İlk tepkin?',
    options: [
      { id: 'hemen', label: 'Çantam beş dakikada hazır, yoldan mesaj atarım' },
      { id: 'planla', label: 'Harika fikir — hafta sonu için planlayalım, düzgün yapalım' },
    ],
    shuffleOptions: true,
    followupPrompt:
      'Hiç plansız çıkılmış bir yolculuğunuz oldu mu? En iyisini ya da en felaket olanını anlatın.',
    aiHint:
      'İki cevap da maceraya açık; fark sadece zamanlamada. "Biri cesur, biri temkinli" çerçevesi kurma.',
    qualityNote:
      'Spontanlığı etiketle değil sahneyle yoklar; "hayır" seçeneği bile iyi planlanmış bir macera olarak yazıldı.',
    answerWeights: {
      hemen: { 'spontanlik': 1.5, 'risk-istahi': 0.5 },
      planla: { 'plan-sevgisi': 1, 'spontanlik': -1 },
    },
    status: 'active',
  },
  {
    slug: 'tatil-aksami-testi',
    category: 'kesif',
    subcategory: 'tatil ritmi',
    trait: 'plan-sevgisi',
    level: 1,
    intensity: 1,
    type: 'choice',
    estSeconds: 12,
    sparkScore: 4,
    funScore: 4,
    prompt:
      'Tatildesin ve bugün tamamen senin. Akşam olduğunda "harika bir gündü" dedirtecek olan hangisi?',
    options: [
      { id: 'rota', label: 'Haritada yıldızladığım yerlerin hepsini gezmiş olmak' },
      { id: 'kayip', label: 'Plansız sokaklarda kaybolup beklenmedik bir şey keşfetmiş olmak' },
      { id: 'sifir-acele', label: 'Manzara karşısında kitap, uyku ve sıfır acele' },
      { id: 'yerel', label: 'Yerel pazardan garip şeyler alıp bir günlüğüne oralı gibi yaşamak' },
    ],
    shuffleOptions: true,
    followupPrompt:
      'Bu dört akşamdan hangisi hayalinizdeki rotada olurdu? Bir sonraki tatil gününü birlikte kurgulayın.',
    qualityNote:
      'Anket sorusunu akşam muhasebesi sahnesine çevirir; dört seçenek dört farklı zevk, hiçbiri "doğru turist" değil.',
    answerWeights: {
      rota: { 'plan-sevgisi': 1.5 },
      kayip: { 'spontanlik': 1, 'macera-istahi': 1 },
      'sifir-acele': { 'tempo': -1 },
      yerel: { 'merak-tarzi': 1, 'macera-istahi': 0.5 },
    },
    status: 'active',
  },
  {
    slug: 'valiz-zamani',
    category: 'kesif',
    subcategory: 'yolculuk hazırlığı',
    trait: 'plan-sevgisi',
    level: 1,
    intensity: 1,
    type: 'slider',
    estSeconds: 6,
    sparkScore: 3,
    funScore: 4,
    prompt: 'Yolculuğa bir hafta var. Valiz cephesinde durum ne?',
    slider: {
      min: 1,
      max: 5,
      lowLabel: 'Valiz çoktan hazır, listem de var',
      highLabel: 'Valiz mi? Çıkarken bir çanta doldururum',
    },
    shuffleOptions: false,
    followupPrompt: 'Valizde asla eksik olmayan tuhaf eşyanız ne? İkiniz de birer tane söyleyin.',
    qualityNote:
      'İki uç da karakterli ve övünülebilir; sayı yok, orta nokta ("çoğu hazır, son gece panik") meşru bir konum.',
    answerWeights: {
      low: { 'plan-sevgisi': 1.5 },
      mid: {},
      high: { 'spontanlik': 1, 'plan-sevgisi': -1 },
    },
    status: 'active',
  },
  // Kültür & Eğlence
  {
    slug: 'ezber-film',
    category: 'kultur',
    subcategory: 'izleme alışkanlığı',
    trait: 'konfor-alani',
    level: 1,
    intensity: 1,
    type: 'either_or',
    estSeconds: 8,
    sparkScore: 4,
    funScore: 4,
    prompt: 'Boş bir akşam, bir şey açacaksın. Hangisi daha çok çekiyor?',
    options: [
      {
        id: 'ezber',
        label: 'Yüz kere izlediğim, repliklerini ezbere bildiğim filmim — o bir sarılma gibi',
      },
      {
        id: 'yeni',
        label: 'Hiç izlemediğim bir şey — aynı filmi ikinci kez izlemek bana israf gibi geliyor',
      },
    ],
    shuffleOptions: true,
    followupPrompt:
      'Replikleri ezbere bildiğiniz o yapımı söyleyin — ve neden hiç eskimediğini savunun.',
    qualityNote:
      'Liste sorusu yerine izleme davranışını sorar; "sarılma gibi" ve "israf gibi" ifadeleri iki tarafı duygusal olarak eşitler.',
    answerWeights: {
      ezber: { 'konfor-alani': 1, 'nostalji-bagi': 0.5 },
      yeni: { 'merak-tarzi': 1, 'konfor-alani': -1 },
    },
    status: 'active',
  },
  {
    slug: 'yeni-sarki-refleksi',
    category: 'kultur',
    subcategory: 'müzik davranışı',
    trait: 'paylasim-istahi',
    level: 1,
    intensity: 1,
    type: 'choice',
    estSeconds: 12,
    sparkScore: 4,
    funScore: 4,
    prompt: 'Çok sevdiğin yeni bir şarkı keşfettin. Büyük ihtimalle sonra ne olur?',
    options: [
      { id: 'tuket', label: 'Tükenene kadar üst üste dinlerim, sonra bir süre küsüşürüz' },
      { id: 'gonder', label: 'Anında birine gönderirim — güzel şey paylaşınca güzel' },
      { id: 'sakla', label: 'Sessizce kendi listeme eklerim; o artık benim sırrım' },
      { id: 'arsiv', label: 'Sanatçının bütün arşivine dalarım, gece orada biter' },
    ],
    shuffleOptions: true,
    followupPrompt:
      'Birbirinize "bunu keşfettiğimde kimseye söylemedim" dediğiniz bir şarkı gönderin.',
    qualityNote:
      'Zevk değil davranış sorusu; "ne dinlersin?" performans baskısını atlar. Farklı cevaplar "bana da gönderir misin?" kapısını açar.',
    answerWeights: {
      tuket: { 'ritual-bagliligi': 0.5 },
      gonder: { 'paylasim-istahi': 1.5 },
      sakla: { 'paylasim-istahi': -1 },
      arsiv: { 'merak-tarzi': 1 },
    },
    status: 'active',
  },
  // Nostalji & Çocukluk
  {
    slug: 'yaz-tatili-karesi',
    category: 'nostalji',
    subcategory: 'çocukluk yazları',
    trait: 'nostalji-bagi',
    level: 1,
    intensity: 1,
    type: 'choice',
    estSeconds: 12,
    sparkScore: 4,
    funScore: 5,
    prompt: 'Çocukluğundaki yaz tatillerini düşün. Aklına ilk gelen kare hangisine daha yakın?',
    options: [
      { id: 'memleket', label: 'Memleket, akraba kalabalığı, kuzenler ordusu' },
      { id: 'mahalle', label: 'Mahalle: akşam karanlığına kadar sokak, "eve gel" seslenişleri' },
      { id: 'deniz', label: 'Deniz, güneş kremi kokusu, ıslak havlu' },
      { id: 'ev', label: 'Serin ev hâli: çizgi filmler, kitaplar, uzun öğle uykuları' },
    ],
    shuffleOptions: true,
    followupPrompt:
      'Gözünüzü kapatın: çocukluk yazlarından tek bir koku ya da ses seçin, birbirinize anlatın.',
    qualityNote:
      'Hatırlama anının kendisi keyifli; seçenekler etiket değil görüntü ve koku üzerinden yazıldı, cevap otomatik anı anlattırır.',
    answerWeights: {
      memleket: { 'nostalji-bagi': 1 },
      mahalle: { 'nostalji-bagi': 1 },
      deniz: { 'nostalji-bagi': 0.5 },
      ev: { 'nostalji-bagi': 0.5, 'alan-ihtiyaci': 0.5 },
    },
    status: 'active',
  },
  {
    slug: 'ilk-harclik',
    category: 'nostalji',
    subcategory: 'ilk’ler',
    trait: 'para-keyif-dengesi',
    level: 1,
    intensity: 1,
    type: 'either_or',
    estSeconds: 8,
    sparkScore: 3,
    funScore: 4,
    prompt:
      'Çocukluğuna dön: eline ilk kez gerçekten "senin" olan bir para geçti. Sen hangi çocuktun?',
    options: [
      { id: 'harcadi', label: 'O para akşama yoktu — neye gittiğini sorma, hatırlamıyorum' },
      { id: 'biriktirdi', label: 'Kumbara müdürü — biriktirmenin kendisi ayrı bir oyundu' },
    ],
    shuffleOptions: true,
    followupPrompt: 'İlk "kendi paranızla" aldığınız şeyi hatırlıyor musunuz? İkiniz de anlatın.',
    aiHint:
      'Bu çocukluk anısıdır, bugünün finansal profili değil; yetişkin para yorumu yapma.',
    qualityNote:
      'Para eğilimini yetişkin finansı sormadan çocukluk sahnesine indirir: güvenli, tatlı, yine de kalıcı bir eğilimin ilk fotoğrafı.',
    answerWeights: {
      harcadi: { 'para-keyif-dengesi': -1, 'spontanlik': 0.5 },
      biriktirdi: { 'para-keyif-dengesi': 1, 'plan-sevgisi': 0.5 },
    },
    status: 'active',
  },
  {
    slug: 'gecmisle-aran',
    category: 'nostalji',
    subcategory: 'geçmişle ilişki',
    trait: 'nostalji-bagi',
    level: 1,
    intensity: 2,
    type: 'slider',
    estSeconds: 8,
    sparkScore: 3,
    funScore: 3,
    prompt: 'Geçmişle aran nasıl?',
    slider: {
      min: 1,
      max: 5,
      lowLabel: 'Eski fotoğraflar, eski şarkılar — arada oraya taşınırım',
      highLabel: 'Güzeldi, bitti; ben hep sıradakine bakarım',
    },
    shuffleOptions: false,
    followupPrompt: 'Dönüp dönüp baktığınız bir fotoğraf ya da şarkı var mı? Neden o?',
    aiHint: 'İki uç da romantize edilebilir: duygusal derinlik vs ileri bakış. Birini olgun gösterme.',
    qualityNote:
      'Gerçek bir spektrum; setin en düşündüren sorusu olarak zorluk 2, eğride ortalarda durmalı.',
    answerWeights: {
      low: { 'nostalji-bagi': 1.5 },
      mid: {},
      high: { 'nostalji-bagi': -1 },
    },
    status: 'active',
  },
  // Günlük Ritim
  {
    slug: 'hediye-saat',
    category: 'ritim',
    subcategory: 'sabah/gece',
    trait: 'sabah-gece-ritmi',
    level: 1,
    intensity: 1,
    type: 'either_or',
    estSeconds: 8,
    sparkScore: 4,
    funScore: 4,
    prompt:
      'Dünya sana günde bir saat hediye etti: herkes uyurken sen uyanıksın. Bu saati günün hangi ucuna eklersin?',
    options: [
      { id: 'sabah', label: 'Sabaha — gün doğarken dünya sadece benimken' },
      { id: 'gece', label: 'Geceye — herkes susunca asıl ben başlarım' },
    ],
    shuffleOptions: true,
    followupPrompt:
      'O hediye saatte tam olarak ne yapardınız? Sabahçı ve gececi birbirine kendi saatini anlatsın.',
    qualityNote:
      'Klişe "sabah insanı mısın?" sorusunun hediye-saat fantezisiyle bükülmüş hâli; iki uç da imrenilecek bir sahne.',
    answerWeights: {
      sabah: { 'sabah-gece-ritmi': -1 },
      gece: { 'sabah-gece-ritmi': 1 },
    },
    status: 'active',
  },
  {
    slug: 'bos-pazar',
    category: 'ritim',
    subcategory: 'hafta sonu',
    trait: 'ev-disari-dengesi',
    level: 1,
    intensity: 1,
    type: 'choice',
    estSeconds: 12,
    sparkScore: 4,
    funScore: 4,
    prompt: 'Pazar sabahı uyandın, gün tamamen boş. İçinden ilk gelen ne?',
    options: [
      { id: 'kahvalti', label: 'Kahvaltıyı ciddiye alıp günü ağırdan açmak' },
      { id: 'disari', label: 'Dışarı — boş gün, şehrin benim olduğu gün demek' },
      { id: 'topla', label: 'Bir plan uydurup birilerini toplamak; boş gün ziyan edilmez' },
      { id: 'koltuk', label: 'Boş gün kutsaldır: pijama, koltuk, "bir bölüm daha"' },
    ],
    shuffleOptions: true,
    followupPrompt: 'En son "mükemmel geçti" dediğiniz boş gün nasıldı? Detaylarıyla anlatın.',
    qualityNote:
      'Rehberdeki örnek sahnenin havuz hâli; dört meşru pazar, "tembel pazar" bile kutsal diye çerçevelenerek eşit prestije çekildi.',
    answerWeights: {
      kahvalti: { 'tempo': -1 },
      disari: { 'ev-disari-dengesi': 1, 'macera-istahi': 0.5 },
      topla: { 'enerji-kaynagi': -1, 'grup-rolu': -1 },
      koltuk: { 'ev-disari-dengesi': -1, 'alan-ihtiyaci': 1 },
    },
    status: 'active',
  },
  {
    slug: 'hayat-temposu',
    category: 'ritim',
    subcategory: 'tempo',
    trait: 'tempo',
    level: 1,
    intensity: 1,
    type: 'slider',
    estSeconds: 6,
    sparkScore: 3,
    funScore: 4,
    prompt: 'Genel yaşam tempon hangi uca yakın?',
    slider: {
      min: 1,
      max: 5,
      lowLabel: 'Aceleye gelmem; dünya beklesin',
      highLabel: 'Bekleyemem; yürüyen merdivende de yürürüm',
    },
    shuffleOptions: false,
    followupPrompt:
      'Hanginiz kimi beklerken sabırsızlanırdı? Birlikte yavaşlamanız ya da hızlanmanız gereken bir an hayal edin.',
    qualityNote:
      '"Yürüyen merdivende de yürürüm" somut ve komik bir davranış imzası; soyut sıfat yerine görüntü verir.',
    answerWeights: {
      low: { 'tempo': -1.5 },
      mid: {},
      high: { 'tempo': 1.5 },
    },
    status: 'active',
  },
  // Hayaller & Olasılıklar
  {
    slug: 'bir-gunluk-hayat',
    category: 'hayal',
    subcategory: 'hayat değişimi',
    trait: 'macera-istahi',
    level: 1,
    intensity: 2,
    type: 'choice',
    estSeconds: 15,
    sparkScore: 4,
    funScore: 5,
    prompt:
      'Bir günlüğüne bambaşka bir hayatı yaşayabilirsin; hafızan ve kimliğin sende kalıyor. Hangisini seçerdin?',
    options: [
      { id: 'sahne', label: 'Dünya turnesindeki bir grubun sahneye çıktığı gece' },
      { id: 'sahaf', label: 'Kıyı kasabasında küçük bir sahaf-kafenin sıradan salı günü' },
      { id: 'uzay', label: 'Uzay istasyonunda bir gün — evet, tuvaleti dahil' },
      { id: 'mutfak', label: 'Büyük bir mutfakta akşam servisinin tam ortası' },
    ],
    shuffleOptions: true,
    followupPrompt: 'Seçtiğiniz hayatın o gününde ilk yapacağınız şey ne olurdu?',
    qualityNote:
      'Düşük risk, yüksek hayal gücü; seçenekler adrenalin/huzur/merak/tutku eksenlerine dağılır. "Tuvaleti dahil" fanteziye gerçeklik göz kırpması.',
    answerWeights: {
      sahne: { 'macera-istahi': 1, 'enerji-kaynagi': -0.5 },
      sahaf: { 'macera-istahi': -1, 'tempo': -0.5 },
      uzay: { 'macera-istahi': 1.5, 'merak-tarzi': 1 },
      mutfak: { 'macera-istahi': 0.5 },
    },
    status: 'active',
  },
  {
    slug: 'mutevazi-super-guc',
    category: 'hayal',
    subcategory: 'süper güç',
    trait: 'macera-istahi',
    level: 1,
    intensity: 1,
    type: 'either_or',
    estSeconds: 10,
    sparkScore: 5,
    funScore: 5,
    prompt: 'İki kusurlu süper güçten birini seçmek zorundasın. Hangisi?',
    options: [
      { id: 'ucus', label: 'Uçabilirsin — ama yürüme hızında' },
      { id: 'isinlanma', label: 'Işınlanabilirsin — ama sadece daha önce gittiğin bir yere' },
    ],
    shuffleOptions: true,
    followupPrompt:
      'Savunma turu: kendi gücünüzün neden açıkça daha iyi olduğuna birbirinizi ikna etmeye çalışın.',
    qualityNote:
      'Klişe süper güç sorusunun kusur eklenerek bükülmüş hâli: kusurlar seçimi gerçek bir tartıya çevirir, savunma turu garantidir.',
    answerWeights: {
      ucus: { 'macera-istahi': 1, 'tempo': -0.5 },
      isinlanma: { 'konfor-alani': 0.5, 'plan-sevgisi': 0.5 },
    },
    status: 'active',
  },
  {
    slug: 'bir-yil-izin',
    category: 'hayal',
    subcategory: 'zaman hediyesi',
    trait: 'oncelik-pusulasi',
    level: 1,
    intensity: 2,
    type: 'choice',
    estSeconds: 15,
    sparkScore: 4,
    funScore: 4,
    prompt: 'Sana bir yıl izin verildi, geçim derdi yok. Ertesi sabah ilk hamlen ne olurdu?',
    options: [
      { id: 'bilet', label: 'Tek yön bilet; gerisini yolda çözerim' },
      { id: 'ogren', label: 'Hep ertelediğim o şeyi öğrenmeye yazılırım' },
      { id: 'sevdikler', label: 'Sevdiklerime uzun kahvaltılar borcum var; ödemeye başlarım' },
      { id: 'proje', label: 'Bir hafta dinlenirim, sonra dayanamayıp kendime bir proje açarım' },
    ],
    shuffleOptions: true,
    followupPrompt: 'O "hep ertelediğim şey" ne? İkiniz de birer tane itiraf edin.',
    qualityNote:
      'Önceliklerin hayal çerçevesinde güvenli ön izlemesi: kimse hayat planını savunmak zorunda kalmaz ama cevaplar çok şey anlatır.',
    answerWeights: {
      bilet: { 'macera-istahi': 1, 'oncelik-pusulasi': -1 },
      ogren: { 'merak-tarzi': 1, 'oncelik-pusulasi': 0.5 },
      sevdikler: { 'oncelik-pusulasi': 1 },
      proje: { 'oncelik-pusulasi': -0.5, 'plan-sevgisi': 0.5 },
    },
    status: 'active',
  },
  // Küçük İtiraflar
  {
    slug: 'gizli-keyif',
    category: 'itiraf',
    subcategory: 'suçlu zevkler',
    trait: 'kucuk-keyifler',
    level: 1,
    intensity: 1,
    type: 'choice',
    estSeconds: 12,
    sparkScore: 4,
    funScore: 5,
    prompt: 'Herkesin kimseye pek anlatmadığı küçük bir keyfi vardır. Seninki hangi bölgeden?',
    options: [
      { id: 'dizi', label: 'Yaşıma sorulmayacak diziler/filmler — ve hiç pişman değilim' },
      { id: 'sarki', label: 'Utanç verici derecede yapışkan şarkılar; listede gizli klasördeler' },
      { id: 'internet', label: 'İnternetin tuhaf köşeleri — buna araştırma diyelim' },
      { id: 'yemek', label: 'Aşırı spesifik bir yeme-içme tuhaflığı; sormayın, yaşıyorum' },
    ],
    shuffleOptions: true,
    followupPrompt:
      'Cesaret turu: gizli keyfinizden birer somut örnek verin. Gülmek serbest, yargı yasak.',
    qualityNote:
      'Karşılıklı küçük itiraf, hızlı yakınlık üreten en güvenli mekanizma; seçenekler kategori verir, teşhiri kullanıcıya bırakır.',
    answerWeights: {
      dizi: { 'kucuk-keyifler': 1 },
      sarki: { 'kucuk-keyifler': 1 },
      internet: { 'merak-tarzi': 0.5, 'kucuk-keyifler': 1 },
      yemek: { 'kucuk-keyifler': 1 },
    },
    status: 'active',
  },
  {
    slug: 'mesaj-itirafi',
    category: 'itiraf',
    subcategory: 'dijital alışkanlık',
    trait: 'temas-ritmi',
    level: 1,
    intensity: 1,
    type: 'either_or',
    estSeconds: 8,
    sparkScore: 4,
    funScore: 4,
    prompt: 'Dürüstlük anı: mesajlaşmada sen hangisisin?',
    options: [
      { id: 'sonra', label: '"Sonra cevaplarım" deyip üç gün sonra utançla dönen benim' },
      { id: 'aninda', label: 'Yazışma yarım kalamaz; okundu bilgim dürüsttür, cevabım anında' },
    ],
    shuffleOptions: true,
    followupPrompt:
      'Telefonunuzdaki en eski "cevaplanacaklar" mesajı ne kadar eski? Dürüstlük turu.',
    aiHint:
      'Bu bir arkadaşlık alışkanlığı itirafıdır; ilişki beklentisi yorumu yapma, geç cevabı kusur olarak çerçeveleme.',
    qualityNote:
      'Mesajlaşma beklentisini sormadan herkesin bildiği alışkanlığı itiraf çerçevesinde sorar; kusur komikleştirilerek güvenli kılındı.',
    answerWeights: {
      sonra: { 'temas-ritmi': 1 },
      aninda: { 'temas-ritmi': -1 },
    },
    status: 'active',
  },
  {
    slug: 'ev-konseri',
    category: 'itiraf',
    subcategory: 'yalnız hâller',
    trait: 'kucuk-keyifler',
    level: 1,
    intensity: 1,
    type: 'slider',
    estSeconds: 6,
    sparkScore: 3,
    funScore: 5,
    prompt: 'Evde yalnızsın ve müzik açtın. Sahne ne durumda?',
    slider: {
      min: 1,
      max: 5,
      lowLabel: 'Fonda çalar, ben işime bakarım',
      highLabel: 'Ev sahneye döner; süpürge mikrofon olabilir',
    },
    shuffleOptions: false,
    followupPrompt: 'Sizi en çok bu moda sokan şarkı hangisi? Birbirinize açın.',
    qualityNote:
      'Herkesin bildiği ama kimsenin sormadığı bir yalnızlık hâli; yüksek uç utanç değil coşku olarak yazıldı. Doğal kapanış sorusu.',
    answerWeights: {
      low: { 'kucuk-keyifler': -0.5 },
      mid: {},
      high: { 'kucuk-keyifler': 1 },
    },
    status: 'active',
  },
  // Sosyal Dünya
  {
    slug: 'tatil-plancisi',
    category: 'sosyal',
    subcategory: 'grup rolü',
    trait: 'grup-rolu',
    level: 1,
    intensity: 1,
    type: 'choice',
    estSeconds: 12,
    sparkScore: 5,
    funScore: 4,
    prompt: 'Arkadaş grubun bir tatil planlıyor. Sen büyük ihtimalle hangisisin?',
    options: [
      { id: 'organizator', label: 'Tabloyu açan, uçuşları bulan, herkesi hizaya sokan organizatör' },
      { id: 'yolcu', label: '"Ben her şeye varım" diyen, planı taşımayan tatlı yolcu' },
      { id: 'revizyoncu', label: 'Son dakika "geliyorum ama şöyle olsa?" diyen revizyoncu' },
      { id: 'moral', label: 'Plana katkısı sıfır ama orada herkesi güldüren moral sorumlusu' },
    ],
    shuffleOptions: true,
    followupPrompt: 'Grup tatillerinden birer efsane anı: plan tutmadığında ne oldu?',
    qualityNote:
      'Kendini dışarıdan görme tipi grup sahnesiyle birleşir; dört rol de sevgiyle yazıldı, roller yan yana gelince espri kendiliğinden doğar.',
    answerWeights: {
      organizator: { 'grup-rolu': -1.5, 'plan-sevgisi': 0.5 },
      yolcu: { 'grup-rolu': 1, 'spontanlik': 0.5 },
      revizyoncu: { 'grup-rolu': 0.5 },
      moral: { 'grup-rolu': 1, 'mizah-tarzi': 1 },
    },
    status: 'active',
  },
  {
    slug: 'gece-sonrasi',
    category: 'sosyal',
    subcategory: 'sosyal enerji',
    trait: 'enerji-kaynagi',
    level: 1,
    intensity: 1,
    type: 'either_or',
    estSeconds: 8,
    sparkScore: 4,
    funScore: 3,
    prompt: 'Kalabalık, güzel bir geceden çıktın. Kapı kapandığı an içindeki his hangisi?',
    options: [
      { id: 'sarj', label: 'Şarj oldum — eve gelince de susamıyorum' },
      { id: 'pil-bitti', label: 'Harikaydı ama pilim bitti; şimdi sessizlik, güzel sessizlik' },
    ],
    shuffleOptions: true,
    followupPrompt: 'İkiniz için de mükemmel bir gece nasıl biter? Saatiyle, sahnesiyle anlatın.',
    aiHint:
      'İki seçenek de geceyi sevmiş durumda; içe dönüklüğü eksiklik gibi yorumlama.',
    qualityNote:
      'İçe/dışa dönüklüğü gece sonrası tek anla sorar; iki seçenek de "gece güzeldi" dediği için sosyal damga yapısal olarak imkânsız.',
    answerWeights: {
      sarj: { 'enerji-kaynagi': -1.5 },
      'pil-bitti': { 'enerji-kaynagi': 1.5, 'alan-ihtiyaci': 0.5 },
    },
    status: 'active',
  },
  // Ev Hâli
  {
    slug: 'kaos-sistemi',
    category: 'ev',
    subcategory: 'düzen',
    trait: 'duzen-kaos',
    level: 1,
    intensity: 1,
    type: 'slider',
    estSeconds: 6,
    sparkScore: 4,
    funScore: 4,
    prompt: 'Yaşam alanın hangi uca yakın?',
    slider: {
      min: 1,
      max: 5,
      lowLabel: 'Her şeyin bir yeri var ve oradadır',
      highLabel: 'Kaos gibi görünür ama içinde bir sistemim var',
    },
    shuffleOptions: false,
    followupPrompt:
      'Birbirinize "benim köşem" dediğiniz alanı tarif edin — kimsenin karışamayacağı bölge.',
    aiHint: 'Düzenli ucu daha olgun gösterme; iki uç da işleyen birer sistemdir.',
    qualityNote:
      'Rehberin slider kuralının birebir uygulaması: "düzenli ↔ dağınık" yargı ekseni "iki farklı sistem" eksenine çevrildi.',
    answerWeights: {
      low: { 'duzen-kaos': -1.5 },
      mid: {},
      high: { 'duzen-kaos': 1.5 },
    },
    status: 'active',
  },
  {
    slug: 'evden-cikmama-gunu',
    category: 'ev',
    subcategory: 'ev günü',
    trait: 'ev-disari-dengesi',
    level: 1,
    intensity: 1,
    type: 'choice',
    estSeconds: 12,
    sparkScore: 3,
    funScore: 4,
    prompt: 'Bugünü resmen "evden çıkmama günü" ilan ettin. Evin en canlı köşesinde ne oluyor?',
    options: [
      { id: 'mutfak', label: 'Mutfak mesaisi: bir şeyler pişiyor, ev güzel kokuyor' },
      { id: 'koltuk', label: 'Koltuk + battaniye + "son bir bölüm" yalanı' },
      { id: 'hobi', label: 'Masaya yayılmış yarım projeler ve hobiler — bugün onların günü' },
      { id: 'balkon', label: 'Balkon/pencere kenarı: ben evdeyim ama gözüm dışarıda' },
    ],
    shuffleOptions: true,
    followupPrompt:
      'Evden çıkmama günlerinizi birleştirseniz o evde neler olurdu? Menüsüyle kurgulayın.',
    qualityNote:
      'Evin en canlı köşesini sorarak mekân üzerinden alışkanlık anlattırır; "son bir bölüm yalanı" öz-ironiyle herkesin hâlini meşrulaştırır.',
    answerWeights: {
      mutfak: { 'ev-disari-dengesi': -1 },
      koltuk: { 'ev-disari-dengesi': -1.5, 'tempo': -0.5 },
      hobi: { 'ev-disari-dengesi': -0.5, 'merak-tarzi': 0.5 },
      balkon: { 'ev-disari-dengesi': 0.5 },
    },
    status: 'active',
  },
  // ── Havuz genişletme: 12 yeni soru ──
  {
    slug: 'buzdolabi-kapagi',
    category: 'ev',
    subcategory: 'günlük alışkanlık',
    trait: 'duzen-kaos',
    level: 1,
    intensity: 1,
    type: 'either_or',
    estSeconds: 8,
    sparkScore: 3,
    funScore: 5,
    prompt: 'Buzdolabının kapağını açtığında nasıl bir manzara karşılıyor seni?',
    options: [
      { id: 'duzen', label: 'Her şey kendi rafında, etiketli bile olabilir' },
      { id: 'kaos', label: 'Tetris oynar gibi bir şeyler sığdırılmış' },
    ],
    shuffleOptions: true,
    followupPrompt: 'Buzdolabı düzeni konusunda biriniz titiz biriniz rahat mı?',
    qualityNote: 'Somut, komik, tartışma açar.',
    answerWeights: {
      duzen: { 'duzen-kaos': -1.5 },
      kaos: { 'duzen-kaos': 1.5 },
    },
    status: 'active',
  },
  {
    slug: 'telefon-alarmi',
    category: 'ritim',
    subcategory: 'sabah',
    trait: 'sabah-gece-ritmi',
    level: 1,
    intensity: 1,
    type: 'choice',
    estSeconds: 10,
    sparkScore: 3,
    funScore: 5,
    prompt: 'Sabah alarmınla aranı en iyi hangisi anlatır?',
    options: [
      { id: 'tek', label: 'Tek alarm, ilk çalışta ayaktayım' },
      { id: 'bes', label: '5 alarm art arda — hepsiyle pazarlık yapıyorum' },
      { id: 'yok', label: 'Alarm kurmam, vücut saatim var' },
      { id: 'erken', label: 'Alarm çalmadan önce uyanırım zaten' },
    ],
    shuffleOptions: true,
    followupPrompt: 'Sabah rutininiz nasıl başlıyor, birbirinize anlatın.',
    qualityNote: 'Evrensel, komik, doğal sohbet açar.',
    answerWeights: {
      tek: { 'sabah-gece-ritmi': -1, 'plan-sevgisi': 0.5 },
      bes: { 'sabah-gece-ritmi': 1 },
      yok: { 'sabah-gece-ritmi': -0.5, spontanlik: 0.5 },
      erken: { 'sabah-gece-ritmi': -1.5 },
    },
    status: 'active',
  },
  {
    slug: 'playlist-tercihi',
    category: 'kultur',
    subcategory: 'müzik',
    trait: 'merak-tarzi',
    level: 1,
    intensity: 1,
    type: 'either_or',
    estSeconds: 8,
    sparkScore: 4,
    funScore: 4,
    prompt: 'Müzik dinlerken daha çok hangisi?',
    options: [
      { id: 'ayni', label: 'Aynı şarkıları tekrar tekrar — hepsini ezbere biliyorum' },
      { id: 'yeni', label: 'Hep yeni müzik arıyorum — keşfetmek heyecan veriyor' },
    ],
    shuffleOptions: true,
    followupPrompt: 'Son keşfettiğiniz veya tekrar tekrar dinlediğiniz bir şarkıyı paylaşın.',
    qualityNote: 'Müzik tercihi merak tarzını yansıtır.',
    answerWeights: {
      ayni: { 'merak-tarzi': -1, 'nostalji-bagi': 0.5 },
      yeni: { 'merak-tarzi': 1.5 },
    },
    status: 'active',
  },
  {
    slug: 'yolda-kaybolmak',
    category: 'hayal',
    subcategory: 'seyahat',
    trait: 'macera-istahi',
    level: 1,
    intensity: 1,
    type: 'either_or',
    estSeconds: 8,
    sparkScore: 4,
    funScore: 4,
    prompt: 'Yeni bir şehirde navigasyon bozuldu. İlk tepkin?',
    options: [
      { id: 'macera', label: 'Harika, en güzel keşifler böyle olur' },
      { id: 'stres', label: 'Hemen birine sorarım veya Wi-Fi ararım' },
    ],
    shuffleOptions: true,
    followupPrompt: 'Kaybolduğunuz ve güzel bir şey keşfettiğiniz bir anınız var mı?',
    qualityNote: 'Belirsizliğe tepki — macera vs güvenlik.',
    answerWeights: {
      macera: { 'macera-istahi': 1.5, 'risk-istahi': 0.5 },
      stres: { 'macera-istahi': -1, 'plan-sevgisi': 0.5 },
    },
    status: 'active',
  },
  {
    slug: 'enerji-saati',
    category: 'ritim',
    subcategory: 'enerji',
    trait: 'enerji-kaynagi',
    level: 1,
    intensity: 1,
    type: 'choice',
    estSeconds: 10,
    sparkScore: 3,
    funScore: 4,
    prompt: 'Gün içinde enerjinin en tepede olduğu zaman dilimi?',
    options: [
      { id: 'sabah', label: 'Sabah ilk saatler — güneşle şarj oluyorum' },
      { id: 'oglen', label: 'Öğleden sonra — motorum geç ısınır' },
      { id: 'aksam', label: 'Akşam saatleri — herkes uyurken ben uyanıyorum' },
      { id: 'degisken', label: 'Güne bağlı — tahmin bile edemem' },
    ],
    shuffleOptions: false,
    followupPrompt: 'Enerji ritminiz uyuyor mu, yoksa farklı saatlerde mi zirve yapıyorsunuz?',
    qualityNote: 'Pratik bilgi, birlikte zaman planlamaya yardımcı.',
    answerWeights: {
      sabah: { 'sabah-gece-ritmi': -1.5 },
      oglen: {},
      aksam: { 'sabah-gece-ritmi': 1.5 },
      degisken: { spontanlik: 0.5 },
    },
    status: 'active',
  },
  {
    slug: 'arkadas-cagri',
    category: 'ritim',
    subcategory: 'sosyal enerji',
    trait: 'sosyal-istah',
    level: 1,
    intensity: 1,
    type: 'slider',
    estSeconds: 10,
    sparkScore: 3,
    funScore: 4,
    prompt: 'Hafta ortası "Bu akşam buluşalım mı?" mesajı geldi. İçinden ne geçer?',
    slider: {
      lowLabel: '"Harika, hemen hazırlanayım!"',
      highLabel: '"Bu akşam mı? Ama benim dizim var..."',
      midLabel: 'Kime göre değişir',
    },
    shuffleOptions: false,
    followupPrompt: 'Spontan buluşma tekliflerine nasıl tepki veriyorsunuz?',
    qualityNote: 'Sosyal iştah ve spontanlık kesişimi.',
    answerWeights: {
      low: { 'sosyal-istah': 1.5, spontanlik: 0.5 },
      mid: {},
      high: { 'sosyal-istah': -1.5, 'alan-ihtiyaci': 0.5 },
    },
    status: 'active',
  },
  {
    slug: 'para-harcama',
    category: 'para',
    subcategory: 'para',
    trait: 'para-keyif-dengesi',
    level: 1,
    intensity: 1,
    type: 'choice',
    estSeconds: 10,
    sparkScore: 4,
    funScore: 4,
    prompt: 'Beklenmedik bir indirim sezonu! En çok hangisine koşarsın?',
    options: [
      { id: 'deneyim', label: 'Konser, etkinlik, seyahat bileti' },
      { id: 'esya', label: 'Uzun süredir baktığım bir ürün' },
      { id: 'biriktir', label: 'İndirim olsa da biriktirmeyi tercih ederim' },
      { id: 'ikram', label: 'Sevdiklerime bir şey alırım' },
    ],
    shuffleOptions: true,
    followupPrompt: 'Para harcama alışkanlıklarınız benziyor mu?',
    qualityNote: 'Harcama tarzı değer sistemiyle bağlantılı.',
    answerWeights: {
      deneyim: { 'para-keyif-dengesi': -1, 'macera-istahi': 0.5 },
      esya: { 'para-keyif-dengesi': -0.5 },
      biriktir: { 'para-keyif-dengesi': 1.5 },
      ikram: { 'paylasim-istahi': 1 },
    },
    status: 'active',
  },
  {
    slug: 'yeni-insanlar',
    category: 'sosyal',
    subcategory: 'tanışma',
    trait: 'guven-inshasi',
    level: 1,
    intensity: 1,
    type: 'slider',
    estSeconds: 10,
    sparkScore: 4,
    funScore: 3,
    prompt: 'Yeni tanıştığın biriyle ne kadar çabuk açılırsın?',
    slider: {
      lowLabel: 'Hemen samimi olurum, hayatımı anlatırım',
      highLabel: 'Yavaş yavaş, güven zamanla olur',
      midLabel: 'Konuya göre değişir',
    },
    shuffleOptions: false,
    followupPrompt: 'Güven inşa etme hızınız birbirinize uyuyor mu?',
    qualityNote: 'Güven inşası Level 1 de ölçülmeye başlar.',
    answerWeights: {
      low: { 'guven-inshasi': -1.5 },
      mid: {},
      high: { 'guven-inshasi': 1.5 },
    },
    status: 'active',
  },
  {
    slug: 'haber-tuketimi',
    category: 'ritim',
    subcategory: 'bilgi',
    trait: 'merak-tarzi',
    level: 1,
    intensity: 1,
    type: 'choice',
    estSeconds: 10,
    sparkScore: 3,
    funScore: 3,
    prompt: 'Haberleri nasıl takip edersin?',
    options: [
      { id: 'aktif', label: 'Her sabah gündem taraması yaparım' },
      { id: 'sosyal', label: 'Sosyal medyada denk gelirse okurum' },
      { id: 'derinlik', label: 'Az ama derinden — uzun analizler okurum' },
      { id: 'uzak', label: 'Haberlerden uzak durmayı tercih ederim' },
    ],
    shuffleOptions: true,
    followupPrompt: 'Bilgi tüketim tarzınız nasıl farklılık gösteriyor?',
    qualityNote: 'Bilgi işleme ve merak tarzı ayrımı.',
    answerWeights: {
      aktif: { 'merak-tarzi': 0.5, tempo: 0.5 },
      sosyal: {},
      derinlik: { 'merak-tarzi': -1.5 },
      uzak: { 'konfor-alani': 0.5 },
    },
    status: 'active',
  },
  {
    slug: 'surpriz-tepki',
    category: 'hayal',
    subcategory: 'tepki',
    trait: 'spontanlik',
    level: 1,
    intensity: 1,
    type: 'either_or',
    estSeconds: 8,
    sparkScore: 4,
    funScore: 5,
    prompt: 'Doğum gününde sürpriz parti yapılsa?',
    options: [
      { id: 'sever', label: 'Bayılırım! Ne güzel bir sürpriz!' },
      { id: 'sevmez', label: 'İçimden "keşke söyleselerdi" derim' },
    ],
    shuffleOptions: true,
    followupPrompt: 'Sürprizlerle aranız nasıl?',
    qualityNote: 'Spontanlık ve kontrol ihtiyacı ayrımı.',
    answerWeights: {
      sever: { spontanlik: 1.5, 'enerji-kaynagi': -0.5 },
      sevmez: { spontanlik: -1, 'plan-sevgisi': 0.5 },
    },
    status: 'active',
  },
  {
    slug: 'yardim-isteme',
    category: 'iletisim',
    subcategory: 'iletişim',
    trait: 'ifade-tarzi',
    level: 1,
    intensity: 1,
    type: 'either_or',
    estSeconds: 8,
    sparkScore: 4,
    funScore: 3,
    prompt: 'Bir konuda yardıma ihtiyacın var. Ne yaparsın?',
    options: [
      { id: 'sorar', label: 'Hemen sorarım, tek başıma uğraşmam' },
      { id: 'dener', label: 'Önce kendim çözmeye çalışırım, olmazsa sorarım' },
    ],
    shuffleOptions: true,
    followupPrompt: 'Yardım isteme konusunda birbirinize benziyor musunuz?',
    qualityNote: 'Bağımsızlık vs paylaşım eğilimi.',
    answerWeights: {
      sorar: { 'ifade-tarzi': -1, 'paylasim-istahi': 0.5 },
      dener: { 'ifade-tarzi': 1, 'alan-ihtiyaci': 0.5 },
    },
    status: 'active',
  },
  {
    slug: 'film-secimi',
    category: 'sosyal',
    subcategory: 'eğlence',
    trait: 'grup-rolu',
    level: 1,
    intensity: 1,
    type: 'choice',
    estSeconds: 10,
    sparkScore: 3,
    funScore: 5,
    prompt: 'Akşam film izlenecek ama kimse karar veremiyor. Sen ne yaparsın?',
    options: [
      { id: 'sec', label: '"Tamam ben seçiyorum" der, filmi belirlerim' },
      { id: 'oner', label: '3 seçenek sunarım, oylama yaparız' },
      { id: 'uyum', label: '"Ne izlersek izleyelim, fark etmez" derim' },
      { id: 'anket', label: 'Gruba anket atarım — demokratik olsun' },
    ],
    shuffleOptions: true,
    followupPrompt: 'Karar alma süreçlerinde kim daha çok inisiyatif alıyor?',
    qualityNote: 'Günlük karar alma ve grup rolü.',
    answerWeights: {
      sec: { 'grup-rolu': -1.5, tempo: 0.5 },
      oner: { 'grup-rolu': -0.5, 'plan-sevgisi': 0.5 },
      uyum: { 'grup-rolu': 1.5 },
      anket: { 'grup-rolu': 0.5 },
    },
    status: 'active',
  },
  // ── 🥚 Easter Egg Soruları — flörtöz, eğlenceli, sürpriz ──
  {
    slug: 'ilk-mesaj',
    category: 'itiraf',
    subcategory: 'easter-egg',
    trait: 'ifade-tarzi',
    level: 1,
    intensity: 2,
    type: 'choice',
    estSeconds: 12,
    sparkScore: 5,
    funScore: 5,
    prompt: '🥚 Bu uygulamada değil de bir dating app\'te karşılaşsaydınız, ilk mesajın ne olurdu?',
    options: [
      { id: 'emoji', label: 'Sadece 🔥 atardım — gerisini merak etsin' },
      { id: 'espri', label: 'Profilindeki bir detayla ilgili espri yapardım' },
      { id: 'soru', label: '"Sence bu uygulama mı yoksa kader mi?" yazardım' },
      { id: 'direkt', label: '"Merhaba, tanışalım mı?" — net ve direkt' },
    ],
    shuffleOptions: true,
    followupPrompt: 'Peki karşı taraf ne yazardı sana? Tahmin et 😏',
    qualityNote: 'Easter egg — direkt karşı tarafa yönelik, cesur.',
    answerWeights: {
      emoji: { 'ifade-tarzi': 1 },
      espri: { 'mizah-tarzi': 1, 'merak-tarzi': 0.5 },
      soru: { 'mizah-tarzi': 0.5 },
      direkt: { 'ifade-tarzi': -1.5 },
    },
    status: 'active',
  },
  {
    slug: 'red-flag',
    category: 'itiraf',
    subcategory: 'easter-egg',
    trait: 'risk-istahi',
    level: 1,
    intensity: 2,
    type: 'choice',
    estSeconds: 10,
    sparkScore: 5,
    funScore: 5,
    prompt: '🥚 Karşındaki kişi hakkında hangi cevabı görünce "vay be" derdin?',
    options: [
      { id: 'macera', label: '"Gece yarısı araba sürmek" seçmesi — cesur biri' },
      { id: 'plan', label: '"Gün gün plan yaparım" seçmesi — düzenli biri' },
      { id: 'espri', label: 'Bir soruya komik cevap vermesi — mizahı var' },
      { id: 'derin', label: 'Derin ve düşündüren bir cevap vermesi' },
    ],
    shuffleOptions: true,
    followupPrompt: 'Karşı tarafın hangi cevabı seni şaşırttı? Söyle bakalım 👀',
    qualityNote: 'Easter egg — karşı tarafın cevaplarına merak uyandırır.',
    answerWeights: {
      macera: { 'risk-istahi': 0.5, 'macera-istahi': 0.5 },
      plan: { 'plan-sevgisi': 0.5 },
      espri: { 'mizah-tarzi': 0.5 },
      derin: { 'merak-tarzi': -0.5 },
    },
    status: 'active',
  },
  {
    slug: 'ilgi-gostermek',
    category: 'itiraf',
    subcategory: 'easter-egg',
    trait: 'paylasim-istahi',
    level: 1,
    intensity: 2,
    type: 'choice',
    estSeconds: 10,
    sparkScore: 5,
    funScore: 5,
    prompt: '🥚 Karşındaki kişiyle bir kafede oturuyorsun. Sohbet çok iyi gidiyor. Ne yaparsın?',
    options: [
      { id: 'uzat', label: '"Bir kahve daha alalım mı?" — bitmesin isterim' },
      { id: 'numara', label: 'Numarasını isterim — devamı olsun' },
      { id: 'bekle', label: 'Bir şey söylemem, o adım atsın isterim' },
      { id: 'plan', label: '"Bir dahaki sefere şuraya gidelim" derim — plan yaparım' },
    ],
    shuffleOptions: true,
    followupPrompt: 'Peki bu kafede şu an oturuyor olsanız hangisini yapardınız? 😉',
    qualityNote: 'Easter egg — hayal kurduruyor, doğrudan karşı tarafla.',
    answerWeights: {
      uzat: { 'paylasim-istahi': 1, tempo: -0.5 },
      numara: { 'ifade-tarzi': -1.5 },
      bekle: { 'ifade-tarzi': 1.5, 'paylasim-istahi': -1 },
      plan: { 'plan-sevgisi': 1, 'ifade-tarzi': -0.5 },
    },
    status: 'active',
  },
  {
    slug: 'ideal-date',
    category: 'hayal',
    subcategory: 'easter-egg',
    trait: 'macera-istahi',
    level: 1,
    intensity: 2,
    type: 'choice',
    estSeconds: 10,
    sparkScore: 5,
    funScore: 5,
    prompt: '🥚 Karşındaki kişiyi bir yere götüreceksin — nereye?',
    options: [
      { id: 'kahve', label: 'Gizli bir kafe — "bunu sadece ben bilirim" havası' },
      { id: 'macera', label: 'Gece şehir turu — nereye çıkarsa' },
      { id: 'yemek', label: 'En sevdiğim restoran — yemek sırasında tanırsın beni' },
      { id: 'manzara', label: 'Manzaralı bir yer — sessizce oturup konuşuruz' },
    ],
    shuffleOptions: true,
    followupPrompt: 'İkiniz de aynı yeri mi seçti? Belki gerçekten gitmelisiniz 👀',
    qualityNote: 'Easter egg — direkt "seni götürüyorum" enerjisi.',
    answerWeights: {
      kahve: { 'paylasim-istahi': 1, 'merak-tarzi': 0.5 },
      macera: { 'macera-istahi': 1.5, spontanlik: 1 },
      yemek: { 'ritual-bagliligi': 0.5, 'paylasim-istahi': 0.5 },
      manzara: { tempo: -0.5, 'alan-ihtiyaci': 0.5 },
    },
    status: 'active',
  },
  {
    slug: 'aciklama-biyografi',
    category: 'sosyal',
    subcategory: 'easter-egg',
    trait: 'mizah-tarzi',
    level: 1,
    intensity: 2,
    type: 'choice',
    estSeconds: 10,
    sparkScore: 5,
    funScore: 5,
    prompt: '🥚 Karşındaki kişiyi 3 kelimeyle anlatman gerekse — henüz bu kadar tanıdığına göre — ne derdin?',
    options: [
      { id: 'merakli', label: 'Meraklı, sıcak, sürpriz' },
      { id: 'sakin', label: 'Sakin, derin, çekici' },
      { id: 'enerjik', label: 'Enerjik, komik, cesur' },
      { id: 'gizemli', label: 'Gizemli, düşünceli, ilginç' },
    ],
    shuffleOptions: true,
    followupPrompt: 'Birbirinizi nasıl tanımladığınızı karşılaştırın — sürpriz olabilir 😏',
    qualityNote: 'Easter egg — karşı tarafı tanımlıyor, dolaylı iltifat.',
    answerWeights: {
      merakli: { 'merak-tarzi': 0.5 },
      sakin: { tempo: -0.5 },
      enerjik: { 'enerji-kaynagi': -0.5 },
      gizemli: { 'ifade-tarzi': 0.5 },
    },
    status: 'active',
  },
  {
    slug: 'yan-yana-sessizlik',
    category: 'itiraf',
    subcategory: 'easter-egg',
    trait: 'alan-ihtiyaci',
    level: 1,
    intensity: 2,
    type: 'either_or',
    estSeconds: 8,
    sparkScore: 5,
    funScore: 5,
    prompt: '🥚 Karşındaki kişiyle yan yana oturup hiç konuşmadan vakit geçirebilir misin?',
    options: [
      { id: 'evet', label: 'Evet — sessizlik de güzel olabilir' },
      { id: 'hayir', label: 'Zor — bir şeyler konuşmam lazım' },
    ],
    shuffleOptions: true,
    followupPrompt: 'Sessizlik testi: şimdi 10 saniye birbirinize bakın, konuşmadan 👀',
    qualityNote: 'Easter egg — cesur follow-up, gerginlik+eğlence.',
    answerWeights: {
      evet: { 'alan-ihtiyaci': 1, 'enerji-kaynagi': 0.5 },
      hayir: { 'temas-ritmi': -0.5 },
    },
    status: 'active',
  },
  {
    slug: 'tahmin-oyunu',
    category: 'hayal',
    subcategory: 'easter-egg',
    trait: 'merak-tarzi',
    level: 1,
    intensity: 2,
    type: 'choice',
    estSeconds: 10,
    sparkScore: 5,
    funScore: 5,
    prompt: '🥚 Karşındaki kişinin bu uygulamada en çok hangi soruyu beğendiğini tahmin et:',
    options: [
      { id: 'komik', label: 'Eğlenceli/komik olanları' },
      { id: 'derin', label: 'Derin ve düşündürenleri' },
      { id: 'kisisel', label: 'Kişisel olanları' },
      { id: 'bu', label: 'Bu soruyu 😂' },
    ],
    shuffleOptions: false,
    followupPrompt: 'Tahmin tuttu mu? Birbirinize sorun — en sevdiğiniz soru hangisiydi?',
    qualityNote: 'Easter egg — meta soru, karşı tarafı düşünmeye itiyor.',
    answerWeights: {
      komik: { 'mizah-tarzi': 0.5 },
      derin: { 'merak-tarzi': -0.5 },
      kisisel: { 'paylasim-istahi': 0.5 },
      bu: { 'mizah-tarzi': 1 },
    },
    status: 'active',
  },
]
