import type { QuestionContent } from '../types'

// Seviye 4 (Ufuk) havuzu — 24 soru.
// Konu: uzun vade, çocuk bakışı, şehir/ülke, kariyer-yaşam dengesi, birlikte büyüme.
// Yasak bölge: kesin karar dili ("bunu yapMALISIN"), travma, eski ilişki dökümü,
// gelir rakamları, sağlık geçmişi, dini/siyasi kimlik.
// Parti kısıtları: kategori başına ≤3, trait başına ≤2,
// 8 ikilem / 10 çoktan seçmeli / 6 slider.
export const level4Questions: QuestionContent[] = [
  // Gelecek & Ufuk (L4 ana kategorisi)
  {
    slug: 'bes-yil-sonra',
    category: 'gelecek',
    subcategory: 'hayat vizyonu',
    trait: 'oncelik-pusulasi',
    level: 4,
    intensity: 1,
    type: 'either_or',
    estSeconds: 10,
    sparkScore: 5,
    funScore: 4,
    prompt: 'Beş yıl sonra kendini hayal ettiğinde, hangisi daha net beliriyor?',
    options: [
      { id: 'yer', label: 'Nerede yaşadığım — şehir, ev, çevre' },
      { id: 'ne', label: 'Ne yaptığım — iş, proje, uğraş' },
    ],
    shuffleOptions: true,
    followupPrompt:
      'Beş yıl sonrasını birbirinize anlat. Resimde neler var?',
    qualityNote:
      'Beş yıl vizyonu L4 ün açılış sorusu; iki seçenek de gelecek odaklı, yargısız.',
    status: 'active',
  },
  {
    slug: 'birlikte-buyume',
    category: 'gelecek',
    subcategory: 'ilişkide gelişim',
    trait: 'temas-ritmi',
    level: 4,
    intensity: 2,
    type: 'choice',
    estSeconds: 12,
    sparkScore: 5,
    funScore: 3,
    prompt: 'Uzun süreli bir ilişkide "birlikte büyümek" senin için ne anlama gelir?',
    options: [
      { id: 'hedef', label: 'Ortak hedeflere doğru birlikte ilerlemek' },
      { id: 'alan', label: 'Birbirimize alan verip kendi yolumuzu bulmak, ama yan yana' },
      { id: 'donusum', label: 'Birbirimizi dönüştürmek — ben sensiz başka biri olurdum' },
      { id: 'destek', label: 'Birbirimizin en zor zamanlarında yanında durmak' },
    ],
    shuffleOptions: true,
    followupPrompt:
      'Sizi en çok büyüten ilişki deneyiminiz ne oldu?',
    qualityNote:
      'Birlikte büyümek L4 derinliğinde; dört tanım da farklı ilişki değerlerini yansıtır.',
    status: 'active',
  },
  {
    slug: 'uzun-vade-temposu',
    category: 'gelecek',
    subcategory: 'tempo tercihi',
    trait: 'koklenme-gocebelik',
    level: 4,
    intensity: 2,
    type: 'slider',
    estSeconds: 6,
    sparkScore: 4,
    funScore: 3,
    prompt: 'Uzun vadede hayatının temposunu nereye ayarlamak istersin?',
    slider: {
      min: 1,
      max: 5,
      lowLabel: 'Sakin ve öngörülebilir — rutin beni rahatlatır',
      highLabel: 'Hareketli ve değişken — monotonluk beni boğar',
    },
    shuffleOptions: false,
    followupPrompt:
      'Hayat temposunu birbirinize anlatın: ideal bir haftanız nasıl görünür?',
    qualityNote:
      'Hayat temposu L4 derinliğinde uzun vade uyumunu yoklar.',
    status: 'active',
  },
  // İletişim & Duygular (L4 derinlik)
  {
    slug: 'tartisma-sonrasi',
    category: 'iletisim',
    subcategory: 'çatışma sonrası',
    trait: 'tartisma-tarzi',
    level: 4,
    intensity: 2,
    type: 'choice',
    estSeconds: 12,
    sparkScore: 5,
    funScore: 3,
    prompt: 'Yakın biriyle ciddi bir tartışma yaşadıktan sonra ilk ne yaparsın?',
    options: [
      { id: 'mesafe', label: 'Mesafe koyarım — soğuyunca daha sağlıklı konuşurum' },
      { id: 'cozum', label: 'Hemen çözmeye çalışırım — yarına taşımak istemem' },
      { id: 'yaz', label: 'Yazarım — ne hissettiğimi kelimelerle ifade etmek bana iyi gelir' },
      { id: 'hareket', label: 'Yürüyüşe çıkarım veya bir şey yaparım — fiziksel olarak boşalmam lazım' },
    ],
    shuffleOptions: true,
    followupPrompt:
      'Tartışma sonrası birbirinize nasıl yaklaşılmasını istersiniz? Şimdi konuşun.',
    aiHint: 'Dört yol da olgun başa çıkma mekanizması; mesafe koymayı kaçış olarak çerçeveleme.',
    qualityNote:
      'Tartışma sonrası L4 derinliğinde çatışma çözümünü yoklar; dört seçenek dört meşru strateji.',
    status: 'active',
  },
  {
    slug: 'affetme-esigi',
    category: 'iletisim',
    subcategory: 'affetme',
    trait: 'ifade-tarzi',
    level: 4,
    intensity: 3,
    type: 'slider',
    estSeconds: 6,
    sparkScore: 5,
    funScore: 2,
    prompt: 'Affetme eşiğin nerede? Güvendiğin biri seni kırdığında...',
    slider: {
      min: 1,
      max: 5,
      lowLabel: 'Kolay affederim; herkes hata yapar, taşımam',
      highLabel: 'Zor affederim; güven bir kere kırılınca tamiri uzun sürer',
    },
    shuffleOptions: false,
    followupPrompt:
      'Affetmekte zorlandığınız bir anınız var mı? Nasıl başa çıktınız?',
    qualityNote:
      'Affetme eşiği L4 ün en derin iletişim sorusu; iki uç da meşru kişilik.',
    status: 'active',
  },
  {
    slug: 'duygu-paylasimi',
    category: 'iletisim',
    subcategory: 'duygusal açıklık',
    trait: 'ifade-tarzi',
    level: 4,
    intensity: 2,
    type: 'either_or',
    estSeconds: 8,
    sparkScore: 5,
    funScore: 3,
    prompt: 'Zor bir döneminden geçerken, çevrendekilere ne kadar açılırsın?',
    options: [
      { id: 'acik', label: 'Paylaşırım — yükü bölmek hafifletir, yalnız taşımak yorar' },
      { id: 'kapali', label: 'Kendi içimde çözerim — başkalarını yormak istemem' },
    ],
    shuffleOptions: true,
    followupPrompt:
      'Zor zamanınızda yanınızda kim olmasını istersiniz? Neden?',
    qualityNote:
      'Duygusal açıklık L4 derinliğinde; iki seçenek de sağlıklı başa çıkma biçimi.',
    status: 'active',
  },
  // Sosyal Dünya (L4 derinlik)
  {
    slug: 'sosyal-cember-gelecek',
    category: 'sosyal',
    subcategory: 'sosyal vizyon',
    trait: 'grup-rolu',
    level: 4,
    intensity: 2,
    type: 'either_or',
    estSeconds: 8,
    sparkScore: 4,
    funScore: 3,
    prompt: 'On yıl sonra sosyal çevren nasıl görünsün istersin?',
    options: [
      { id: 'dar', label: 'Az ama derin — birkaç kişiyle güçlü bağlar' },
      { id: 'genis', label: 'Geniş ve çeşitli — farklı dünyalardan insanlar' },
    ],
    shuffleOptions: true,
    followupPrompt:
      'İdeal sosyal çevrenizde kimler var? Birbirinize hayalinizi çizin.',
    qualityNote:
      'Sosyal vizyon L4 te uzun vadeli sosyal tercihi yoklar.',
    status: 'active',
  },
  {
    slug: 'yakinlarla-sinir',
    category: 'sosyal',
    subcategory: 'sınır koyma',
    trait: 'alan-ihtiyaci',
    level: 4,
    intensity: 3,
    type: 'choice',
    estSeconds: 12,
    sparkScore: 5,
    funScore: 3,
    prompt: 'Aile veya çok yakın bir arkadaş sınırlarını aştığında ne yaparsın?',
    options: [
      { id: 'acik', label: 'Açıkça söylerim — yakınlık sınırsızlık demek değil' },
      { id: 'yumusak', label: 'Yumuşak ama kararlı bir şekilde mesafe koyarım' },
      { id: 'katlan', label: 'Bir süre katlanırım; ama birikince patlarım' },
      { id: 'uzak', label: 'Sessizce uzaklaşırım — çatışma istemem' },
    ],
    shuffleOptions: true,
    followupPrompt:
      'Sınır koyma konusunda zorlandığınız bir durum yaşadınız mı? Nasıl çözdünüz?',
    aiHint: 'Dört tepki de gerçekçi; sessiz uzaklaşmayı pasiflik olarak etiketleme.',
    qualityNote:
      'Sınır koyma L4 derinliğinde; yakın ilişkilerde güvenli çerçevede sorulan zor bir soru.',
    status: 'active',
  },
  {
    slug: 'komsu-etkisi',
    category: 'sosyal',
    subcategory: 'çevre etkisi',
    trait: 'alan-ihtiyaci',
    level: 4,
    intensity: 1,
    type: 'slider',
    estSeconds: 6,
    sparkScore: 3,
    funScore: 4,
    prompt: 'Yaşadığın yerdeki komşularını / mahalleliyi ne kadar önemsersin?',
    slider: {
      min: 1,
      max: 5,
      lowLabel: 'Pek etkilemez; evimin içi yeter',
      highLabel: 'Çok önemli; mahalle benim uzantım',
    },
    shuffleOptions: false,
    followupPrompt:
      'Komşularınızla en güzel anınız ne oldu?',
    qualityNote:
      'Mahalle ve topluluk duygusu L4 te köklenme tercihini hafif bir yerden yoklar.',
    status: 'active',
  },
  // Ev Hâli (L4 derinlik)
  {
    slug: 'ev-hayali',
    category: 'ev',
    subcategory: 'ev vizyonu',
    trait: 'koklenme-gocebelik',
    level: 4,
    intensity: 1,
    type: 'either_or',
    estSeconds: 8,
    sparkScore: 4,
    funScore: 4,
    prompt: 'İdeal evin nasıl bir yer?',
    options: [
      { id: 'sabit', label: 'Bir yere kök salmış; bahçesi, raflarında yılların birikimleri olan bir ev' },
      { id: 'hafif', label: 'Taşınmaya hazır; esnek, hafif, dünyanın her yerinde olabilecek bir yer' },
    ],
    shuffleOptions: true,
    followupPrompt:
      'İdeal evinizi birbirinize çizin: nerede, nasıl, neye bakıyor?',
    qualityNote:
      'Ev hayali L4 te yerleşme-göçebelik tercihini somutlaştırır.',
    status: 'active',
  },
  {
    slug: 'ev-sorumluluk',
    category: 'ev',
    subcategory: 'sorumluluk paylaşımı',
    trait: 'tartisma-tarzi',
    level: 4,
    intensity: 2,
    type: 'choice',
    estSeconds: 12,
    sparkScore: 4,
    funScore: 3,
    prompt: 'Birlikte yaşandığında ev içi sorumluluklar nasıl bölünmeli?',
    options: [
      { id: 'esit', label: 'Eşit ve net — kim ne yapıyor, belli olsun' },
      { id: 'guclü', label: 'Herkes güçlü olduğu işi üstlensin — adalet eşitlik değil' },
      { id: 'donusum', label: 'Dönüşümlü — alışkanlık olmasın, herkes her işi bilsin' },
      { id: 'dogal', label: 'Doğal akışına bıraksın — liste tutmak ilişkiye zarar verir' },
    ],
    shuffleOptions: true,
    followupPrompt:
      'Ev işi paylaşımında en çok neye önem verirsiniz? Birbirinize söyleyin.',
    qualityNote:
      'Sorumluluk paylaşımı L4 te birlikte yaşam vizyonunun pratik boyutunu yoklar.',
    status: 'active',
  },
  {
    slug: 'cocuk-bakisi',
    category: 'ev',
    subcategory: 'aile vizyonu',
    trait: 'konfor-alani',
    level: 4,
    intensity: 3,
    type: 'choice',
    estSeconds: 15,
    sparkScore: 5,
    funScore: 2,
    prompt: 'Çocuk konusu senin için şu an nerede duruyor?',
    options: [
      { id: 'evet', label: 'İstiyorum — hayatımda çocuk olsun istiyorum' },
      { id: 'belki', label: 'Belki — şartlara ve zamana bağlı, şu an net değilim' },
      { id: 'hayir', label: 'İstemiyorum — çocuksuz bir hayat benim için tam' },
      { id: 'dusunmedim', label: 'Henüz ciddi düşünmedim — çok erken' },
    ],
    shuffleOptions: true,
    followupPrompt:
      'Bu konuyu açıkça konuşmak size nasıl hissettirdi? Devam edin.',
    aiHint: 'Dört cevap da meşru ve saygıyla karşılanmalı; hiçbir tercihi üstün gösterme.',
    qualityNote:
      'Çocuk konusu L4 ün en kritik sorularından; güvenli çerçevede, yargısız seçeneklerle sunulmuş.',
    status: 'active',
  },
  // Para & Değer (L4 derinlik)
  {
    slug: 'para-ve-ozgurluk',
    category: 'para',
    subcategory: 'para-özgürlük ilişkisi',
    trait: 'para-keyif-dengesi',
    level: 4,
    intensity: 2,
    type: 'either_or',
    estSeconds: 8,
    sparkScore: 5,
    funScore: 3,
    prompt: 'Para sana ne veriyor aslında?',
    options: [
      { id: 'guvenlik', label: 'Güvenlik — rahat bir gelecek, beklenmedik durumlar için hazırlık' },
      { id: 'ozgurluk', label: 'Özgürlük — istediğimi yapabilmek, "hayır" diyebilmek' },
    ],
    shuffleOptions: true,
    followupPrompt:
      'Paradan bağımsız olsanız, ilk ne yapardınız?',
    qualityNote:
      'Para ve özgürlük L4 te değer derinliğini yoklar; iki çerçeve de meşru.',
    status: 'active',
  },
  {
    slug: 'finansal-ortaklik',
    category: 'para',
    subcategory: 'finansal paylaşım',
    trait: 'para-keyif-dengesi',
    level: 4,
    intensity: 3,
    type: 'choice',
    estSeconds: 12,
    sparkScore: 5,
    funScore: 2,
    prompt: 'Uzun süreli bir ilişkide parasal konular nasıl yönetilmeli?',
    options: [
      { id: 'ortak', label: 'Ortak hesap — her şey şeffaf, birlikte yönetelim' },
      { id: 'ayri', label: 'Ayrı hesaplar — herkesin kendi parası, ortak giderler bölünür' },
      { id: 'karma', label: 'Karma — ortak giderler için bir havuz, geri kalanı kişisel' },
      { id: 'onemli-degil', label: 'Çok erken konuşmak için — önce güven inşa edilmeli' },
    ],
    shuffleOptions: true,
    followupPrompt:
      'Finansal şeffaflık sizin için ne anlama geliyor? Birbirinize anlatın.',
    qualityNote:
      'Finansal ortaklık L4 te birlikte yaşam vizyonunun para boyutu; dört seçenek de meşru.',
    status: 'active',
  },
  // Günlük Ritim (L4)
  {
    slug: 'kariyer-iliski-dengesi',
    category: 'ritim',
    subcategory: 'kariyer-ilişki',
    trait: 'tempo',
    level: 4,
    intensity: 2,
    type: 'slider',
    estSeconds: 6,
    sparkScore: 5,
    funScore: 3,
    prompt: 'Kariyer ve ilişki arasındaki dengeyi nereye koyarsın?',
    slider: {
      min: 1,
      max: 5,
      lowLabel: 'İlişki öncelik — kariyer hayatın bir parçası ama merkezi değil',
      highLabel: 'Kariyer öncelik — kendimi gerçekleştirmem ilişkiden önce gelir',
    },
    shuffleOptions: false,
    followupPrompt:
      'Kariyeriniz için bir ilişkiden vazgeçer misiniz? Ya da tam tersi?',
    qualityNote:
      'Kariyer-ilişki dengesi L4 ün temel ufuk sorularından; spektrum yargısız.',
    status: 'active',
  },
  {
    slug: 'emeklilik-hayali',
    category: 'ritim',
    subcategory: 'uzun vade ritim',
    trait: 'risk-istahi',
    level: 4,
    intensity: 1,
    type: 'either_or',
    estSeconds: 8,
    sparkScore: 4,
    funScore: 4,
    prompt: 'Emeklilik hayalin hangisine daha yakın?',
    options: [
      { id: 'huzur', label: 'Sakin bir köşede, bahçeyle, kitaplarla, huzurlu bir yaşam' },
      { id: 'macera', label: 'Dünyayı gezmek, yeni işler denemek — emeklilik durma değil, yön değiştirme' },
    ],
    shuffleOptions: true,
    followupPrompt:
      'Emeklilik yaşınızda yanınızda ne olsun istersiniz? Birbirinize anlatın.',
    qualityNote:
      'Emeklilik hayali L4 te uzun vadeli yaşam vizyonunu yumuşak bir sahneden yoklar.',
    status: 'active',
  },
  // Seyahat & Keşif (L4)
  {
    slug: 'yasanacak-sehir',
    category: 'kesif',
    subcategory: 'yaşam yeri',
    trait: 'enerji-kaynagi',
    level: 4,
    intensity: 2,
    type: 'choice',
    estSeconds: 12,
    sparkScore: 5,
    funScore: 4,
    prompt: 'Yaşanacak şehri seçerken senin için en belirleyici ne?',
    options: [
      { id: 'aile', label: 'Aileme ve sevdiklerime yakınlık' },
      { id: 'kariyer', label: 'Kariyer fırsatları ve profesyonel gelişim' },
      { id: 'yasam', label: 'Yaşam kalitesi — doğa, iklim, sakinlik' },
      { id: 'kultur', label: 'Kültürel zenginlik — etkinlikler, çeşitlilik, enerji' },
    ],
    shuffleOptions: true,
    followupPrompt:
      'Hayalinizdeki şehri birbirinize tarif edin. Aynı yer mi çıkıyor?',
    qualityNote:
      'Şehir seçimi L4 te yerleşme vizyonunu dört farklı değer üzerinden yoklar.',
    status: 'active',
  },
  {
    slug: 'yurt-disi-yasam',
    category: 'kesif',
    subcategory: 'göç düşüncesi',
    trait: 'risk-istahi',
    level: 4,
    intensity: 2,
    type: 'slider',
    estSeconds: 6,
    sparkScore: 5,
    funScore: 3,
    prompt: 'Yurt dışında yaşamak senin için ne kadar cazip?',
    slider: {
      min: 1,
      max: 5,
      lowLabel: 'Tatil için güzel ama yaşamak istediğim yer burası',
      highLabel: 'Çok cazip — doğru fırsat olsa hemen giderim',
    },
    shuffleOptions: false,
    followupPrompt:
      'Yurt dışında yaşasanız nereyi seçerdiniz? Neden?',
    qualityNote:
      'Yurt dışı yaşam L4 te göçebelik-köklenme tercihini somutlaştırır.',
    status: 'active',
  },
  // Tat & Mutfak (L4)
  {
    slug: 'ozel-gun-sofrasi',
    category: 'lezzet',
    subcategory: 'kutlama tercihi',
    trait: 'paylasim-istahi',
    level: 4,
    intensity: 1,
    type: 'either_or',
    estSeconds: 8,
    sparkScore: 4,
    funScore: 5,
    prompt: 'Özel bir günü kutlarken sofra nasıl olsun?',
    options: [
      { id: 'ozel', label: 'İki kişilik, özenli, sessiz bir akşam yemeği' },
      { id: 'kalabalik', label: 'Sevdiklerimiz de olsun; kutlama paylaşınca güzel' },
    ],
    shuffleOptions: true,
    followupPrompt:
      'En güzel kutlamanız nasıl oldu? Birbirinize en iyi sofra anınızı anlatın.',
    qualityNote:
      'Kutlama tercihi L4 te paylaşım stilini özel gün sahnesinden yoklar.',
    status: 'active',
  },
  {
    slug: 'yemek-mirasi',
    category: 'lezzet',
    subcategory: 'aile mirası',
    trait: 'nostalji-bagi',
    level: 4,
    intensity: 2,
    type: 'choice',
    estSeconds: 12,
    sparkScore: 4,
    funScore: 4,
    prompt: 'Aileden gelen bir yemek geleneğin var mı? Bu gelenek senin için ne ifade ediyor?',
    options: [
      { id: 'devam', label: 'Var ve devam ettiriyorum — beni aileme bağlayan bir köprü' },
      { id: 'ozlem', label: 'Var ama artık yapmıyorum — özlemle hatırlarım' },
      { id: 'yok', label: 'Pek yok — ama kendi geleneklerimi kurmak istiyorum' },
      { id: 'onemli-degil', label: 'Yemek benim için gelenek aracı değil; yakınlığı başka yerde bulurum' },
    ],
    shuffleOptions: true,
    followupPrompt:
      'Birbirinize bir aile yemeği tarif edin. Tadını ve hikâyesini anlatın.',
    qualityNote:
      'Yemek mirası L4 te nostalji bağını gelenek üzerinden yoklar; dört seçenek de pozitif.',
    status: 'active',
  },
  // Kültür & Eğlence (L4)
  {
    slug: 'sanat-etkisi',
    category: 'kultur',
    subcategory: 'kültürel etki',
    trait: 'paylasim-istahi',
    level: 4,
    intensity: 2,
    type: 'choice',
    estSeconds: 12,
    sparkScore: 4,
    funScore: 3,
    prompt: 'Bir film, kitap veya şarkı seni derinden etkilediğinde ne olur?',
    options: [
      { id: 'paylas', label: 'Herkese anlatırım — "bunu mutlaka izle/oku/dinle"' },
      { id: 'icsel', label: 'Kendi içimde yaşarım — o etki benimle kalır, paylaşmam azaltır' },
      { id: 'tekrar', label: 'Tekrar tekrar dönerim — o eser benim bir parçam olur' },
      { id: 'ilham', label: 'Bir şey yaratmak isterim — yazmak, çizmek, bir şekilde karşılık vermek' },
    ],
    shuffleOptions: true,
    followupPrompt:
      'Sizi derinden etkileyen bir eser birbirinize anlatın. Neden bu kadar dokundu?',
    qualityNote:
      'Sanat etkisi L4 derinliğinde; estetik deneyimi farklı kişilik tepkileriyle yoklar.',
    status: 'active',
  },
  // Kültür & Eğlence (L4) — ikinci soru
  {
    slug: 'estetik-hassasiyet',
    category: 'kultur',
    subcategory: 'estetik deneyim',
    trait: 'sabah-gece-ritmi',
    level: 4,
    intensity: 2,
    type: 'slider',
    estSeconds: 6,
    sparkScore: 4,
    funScore: 3,
    prompt: 'Güzellik — müzik, doğa, tasarım, sanat — seni ne kadar etkiler?',
    slider: {
      min: 1,
      max: 5,
      lowLabel: 'Fark ederim ama günümü değiştirmez',
      highLabel: 'Derinden etkiler; güzel bir şey ruh halimi tamamen değiştirir',
    },
    shuffleOptions: false,
    followupPrompt:
      'Son zamanlarda sizi "vay" dedirten bir güzellik anı var mı? Birbirinize anlatın.',
    qualityNote:
      'Estetik hassasiyet L4 te kişilik derinliğini sanat/doğa üzerinden yoklar.',
    status: 'active',
  },
  // Hayaller & Olasılıklar (L4)
  {
    slug: 'hayat-dersi',
    category: 'hayal',
    subcategory: 'bilgelik',
    trait: 'nostalji-bagi',
    level: 4,
    intensity: 3,
    type: 'either_or',
    estSeconds: 10,
    sparkScore: 5,
    funScore: 3,
    prompt: 'Şimdiye kadar hayatın sana öğrettiği en değerli şey ne?',
    options: [
      { id: 'sabir', label: 'Sabır — her şeyin bir zamanı var, acele etmemek' },
      { id: 'cesaret', label: 'Cesaret — korksam da adım atmak, pişmanlığı beklentiye tercih etmek' },
    ],
    shuffleOptions: true,
    followupPrompt:
      'Bu dersi hangi deneyim öğretti? Hikâyenizi birbirinize anlatın.',
    qualityNote:
      'Hayat dersi L4 ün kapanışı; derinlik ve kişisel hikâye tetikler. İyi bir closer adayı.',
    status: 'active',
  },
  {
    slug: 'birlikte-miras',
    category: 'hayal',
    subcategory: 'miras bırakmak',
    trait: 'oncelik-pusulasi',
    level: 4,
    intensity: 3,
    type: 'choice',
    estSeconds: 15,
    sparkScore: 5,
    funScore: 2,
    prompt: 'Geride bırakmak istediğin "iz" ne olurdu?',
    options: [
      { id: 'insan', label: 'İnsanlar — yetiştirdiğim, dokunduğum hayatlar' },
      { id: 'eser', label: 'Bir eser — yazdığım, kurduğum, inşa ettiğim bir şey' },
      { id: 'deger', label: 'Bir değer — ilham verdiğim bir düşünce veya yaşam biçimi' },
      { id: 'an', label: 'An — güzel anılar bırakmak; iz bırakmak zorunda değilim' },
    ],
    shuffleOptions: true,
    followupPrompt:
      'Birbirinize "beni hatırlasınlar" fikri ne kadar önemli? Açıkça konuşun.',
    aiHint: 'Dört seçenek de meşru hayat felsefesi; iz bırakmak istememeyi eksiklik olarak gösterme.',
    qualityNote:
      'Miras sorusu L4 ün en derin sorularından; dört seçenek dört farklı anlam katmanı. Closer adayı.',
    status: 'active',
  },
]
