import type { QuestionContent } from '../types'

// Seviye 2 (Karakter & Ritim) havuzu — 24 soru.
// Konu: para alışkanlıkları, düzen/kaos, sosyal enerji, stres tarzı, günlük ritim detayları.
// Parti kısıtları: kategori başına ≤3, trait başına ≤2,
// 8 ikilem / 10 çoktan seçmeli / 6 slider.
export const level2Questions: QuestionContent[] = [
  // Para Alışkanlıkları
  {
    slug: 'hesap-geldi',
    category: 'para',
    subcategory: 'harcama refleksi',
    trait: 'para-keyif-dengesi',
    level: 2,
    intensity: 1,
    type: 'either_or',
    estSeconds: 8,
    sparkScore: 4,
    funScore: 4,
    prompt:
      'Arkadaş grubuyla güzel bir akşam yemeği. Hesap geldi. Sen hangisisin?',
    options: [
      { id: 'ortala', label: 'Ortadan bölelim, hesap yapmasak rahat ederiz' },
      { id: 'ayri', label: 'Herkes kendininki — bir de başkasının şarabını mı ödeyeceğim?' },
    ],
    shuffleOptions: true,
    followupPrompt:
      'Hesap geldiğinde en tuhaf yaşadığınız anı anlatın. Kim ödedi, nasıl bitti?',
    qualityNote:
      'Para alışkanlığını doğrudan sormak yerine tanıdık bir sahneye oturtur; iki seçenek de meşru ve hafif espri taşır.',
    answerWeights: {
      ortala: { 'para-keyif-dengesi': -0.5, 'paylasim-istahi': 0.5 },
      ayri: { 'para-keyif-dengesi': 1 },
    },
    status: 'active',
  },
  {
    slug: 'pazar-cimriligi',
    category: 'para',
    subcategory: 'harcama tercihi',
    trait: 'para-keyif-dengesi',
    level: 2,
    intensity: 2,
    type: 'choice',
    estSeconds: 12,
    sparkScore: 4,
    funScore: 4,
    prompt: 'Paranı rahat harcadığın şey hangisi, "buna bu kadar verilmez" dediğin hangisi?',
    options: [
      { id: 'yemek', label: 'Yemeğe rahat harcarım, kıyafete "bu kadar mı?" derim' },
      { id: 'deneyim', label: 'Deneyime (konser, tatil) harcarım, eşyada hesap yaparım' },
      { id: 'kiyafet', label: 'Güzel bir parçaya yatırım derim, dışarı yemek gereksiz lüks' },
      { id: 'teknoloji', label: 'Teknolojiye gözümü kırpmam, ama takside gideceksem iki kere düşünürüm' },
    ],
    shuffleOptions: true,
    followupPrompt:
      'En son "buna bu kadar verilir mi?" dediğiniz ama sonra hiç pişman olmadığınız harcama ne?',
    aiHint: 'Harcama tercihi kişilik yansıtır ama doğru/yanlış yoktur; tutumluluğu erdem olarak çerçeveleme.',
    qualityNote:
      'Rakam sormadan harcama refleksini ortaya koyar; kontrast formatı ("şuna evet, buna hayır") sohbet malzemesi üretir.',
    answerWeights: {
      yemek: { 'para-keyif-dengesi': -0.5 },
      deneyim: { 'para-keyif-dengesi': -1, 'macera-istahi': 0.5 },
      kiyafet: { 'para-keyif-dengesi': 0.5 },
      teknoloji: { 'para-keyif-dengesi': 0.5 },
    },
    status: 'active',
  },
  {
    slug: 'beklenmedik-para',
    category: 'para',
    subcategory: 'para psikolojisi',
    trait: 'risk-istahi',
    level: 2,
    intensity: 2,
    type: 'choice',
    estSeconds: 12,
    sparkScore: 4,
    funScore: 5,
    prompt: 'Beklenmedik bir yerden güzel bir para geldi. İlk refleksin hangisine daha yakın?',
    options: [
      { id: 'sakla', label: 'Hiç yokmuş gibi davranıp kenara koyarım — geleceğe hediye' },
      { id: 'harca', label: 'Bedava para harcanır; ertelemek onu sıkıcı yapar' },
      { id: 'borc', label: 'Önce bir borç/yükümlülük kapatırım, sonra rahat ederim' },
      { id: 'paylas', label: 'Birilerine güzel bir sürpriz yapmak için kullanırım' },
    ],
    shuffleOptions: true,
    followupPrompt:
      'Beklenmedik gelen paranın en güzel harcandığı anınızı anlatın.',
    qualityNote:
      'Para psikolojisini somut sahneyle; dört seçenek dört farklı değer sistemini yansıtır, hiçbiri "doğru" değil.',
    answerWeights: {
      sakla: { 'risk-istahi': -1.5, 'plan-sevgisi': 0.5 },
      harca: { 'risk-istahi': 1, 'spontanlik': 0.5 },
      borc: { 'risk-istahi': -0.5, 'plan-sevgisi': 1 },
      paylas: { 'paylasim-istahi': 1 },
    },
    status: 'active',
  },
  // Sosyal Dünya (L2 derinlik)
  {
    slug: 'kalabalik-enerji',
    category: 'sosyal',
    subcategory: 'sosyal enerji yönetimi',
    trait: 'sosyal-istah',
    level: 2,
    intensity: 1,
    type: 'slider',
    estSeconds: 6,
    sparkScore: 3,
    funScore: 4,
    prompt: 'Haftalık sosyal enerjin nasıl dağılır?',
    slider: {
      min: 1,
      max: 5,
      lowLabel: 'Haftada bir-iki buluşma yeter, arada şarj lazım',
      highLabel: 'Boş akşam istemem; her gün biri bir yerde',
    },
    shuffleOptions: false,
    followupPrompt:
      'Bir haftanızı birlikte planlasanız, kaç akşam dışarıda olurdunuz? Üzerinde anlaşın.',
    qualityNote:
      "L1'deki gece-sonrası sorusunun bir katman altı; sosyal iştahı daha doğrudan ama yine yargısız ölçer.",
    answerWeights: {
      low: { 'sosyal-istah': -1.5, 'alan-ihtiyaci': 1 },
      mid: {},
      high: { 'sosyal-istah': 1.5, 'enerji-kaynagi': -0.5 },
    },
    status: 'active',
  },
  {
    slug: 'davet-refleksi',
    category: 'sosyal',
    subcategory: 'plan tercihi',
    trait: 'spontanlik',
    level: 2,
    intensity: 2,
    type: 'either_or',
    estSeconds: 8,
    sparkScore: 4,
    funScore: 4,
    prompt: 'Cuma akşamı planın yok. Telefon çaldı: "Yarım saate geliyoruz, hazır ol." Hangisi?',
    options: [
      { id: 'hadi', label: 'Tamam! Beş dakikaya hazırım, nereye gidiyoruz?' },
      { id: 'uyari', label: 'Geleceğinizi önceden söyleseniz keşke — ama bu sefer tamam' },
    ],
    shuffleOptions: true,
    followupPrompt:
      'Son dakika planlarınızdan biri güzel mi bitti, felaket mi? Anlatın.',
    aiHint: 'İki cevap da sosyal birini gösterir; fark sadece hazırlık ihtiyacında.',
    qualityNote:
      'L1 spontanlığını (gece-yolculugu-teklifi) daha gündelik bir sahneye taşır; "bu sefer tamam" seçeneği kapıyı tamamen kapatmaz.',
    answerWeights: {
      hadi: { 'spontanlik': 1.5 },
      uyari: { 'spontanlik': -0.5, 'plan-sevgisi': 0.5 },
    },
    status: 'active',
  },
  {
    slug: 'tartisma-stili',
    category: 'sosyal',
    subcategory: 'çatışma yönetimi',
    trait: 'tartisma-tarzi',
    level: 2,
    intensity: 2,
    type: 'choice',
    estSeconds: 12,
    sparkScore: 5,
    funScore: 3,
    prompt: 'Arkadaşınla bir konuda ters düştünüz. Senin doğal refleksin hangisi?',
    options: [
      { id: 'hemen', label: 'Hemen konuşalım — çözülmemiş mesele kafamda büyür' },
      { id: 'bekle', label: 'Biraz bekleyeyim, sakinleşince daha iyi anlatırım' },
      { id: 'yaz', label: 'Yazarak daha iyi ifade ederim; uzun mesaj atacağım' },
      { id: 'ges', label: 'Büyütmem — çoğu şey birkaç gün sonra kendiliğinden ufalar' },
    ],
    shuffleOptions: true,
    followupPrompt:
      'Tartışma tarzlarınızı kıyaslayın: hanginiz daha çabuk konuşur, hanginiz daha çok bekler?',
    aiHint:
      'Dört tarz da sağlıklı olabilir; "kaçınma" veya "yüzleşme sorunu" çerçevesi kurma.',
    qualityNote:
      'L2 derinliğinde çatışma yönetimi — arkadaşlık çerçevesinde sorularak güvenli kalır. Dört stil de olgun.',
    answerWeights: {
      hemen: { 'tartisma-tarzi': -1.5, 'ifade-tarzi': -0.5 },
      bekle: { 'tartisma-tarzi': 1, 'alan-ihtiyaci': 0.5 },
      yaz: { 'tartisma-tarzi': 0.5, 'ifade-tarzi': 1 },
      ges: { 'tartisma-tarzi': 1.5 },
    },
    status: 'active',
  },
  // Ev Hâli (L2 derinlik)
  {
    slug: 'misafir-gelecek',
    category: 'ev',
    subcategory: 'ev düzeni',
    trait: 'duzen-kaos',
    level: 2,
    intensity: 1,
    type: 'either_or',
    estSeconds: 8,
    sparkScore: 4,
    funScore: 5,
    prompt: 'Misafir gelecek diye ev toplamak: sen hangisisin?',
    options: [
      { id: 'panik', label: 'Panik temizlik — bu hâlim vitrin modu, yemin ederim' },
      { id: 'rahat', label: 'Olduğu gibi gelsinler; bu kadar yakın değilsek zaten gelmesinler' },
    ],
    shuffleOptions: true,
    followupPrompt:
      'Misafir gelmeden önce sakladığınız en komik eşya ne? İtiraf turu.',
    qualityNote:
      'L1 kaos-sistemi sorusunun somut sahneye taşınmış hâli; iki seçenek de güldürür.',
    answerWeights: {
      panik: { 'duzen-kaos': -1 },
      rahat: { 'duzen-kaos': 1.5 },
    },
    status: 'active',
  },
  {
    slug: 'ortak-alan-kurali',
    category: 'ev',
    subcategory: 'alan paylaşımı',
    trait: 'alan-ihtiyaci',
    level: 2,
    intensity: 2,
    type: 'choice',
    estSeconds: 12,
    sparkScore: 5,
    funScore: 4,
    prompt: 'Biriyle aynı evi paylaşsan, senin için en önemli kural hangisi olurdu?',
    options: [
      { id: 'sessizlik', label: 'Sessizlik saatleri — bazı saatler kutsal ve dokunulmaz' },
      { id: 'mutfak', label: 'Mutfak düzeni — bulaşık kuralları evrensel anayasadır' },
      { id: 'alan', label: 'Kişisel alan — benim köşem, benim kurallarım' },
      { id: 'spontan', label: 'Tek kural: kural olmasın, konuşarak çözeriz' },
    ],
    shuffleOptions: true,
    followupPrompt:
      'Ev arkadaşı hikâyelerinden en iyi ve en kötü senaryoyu paylaşın.',
    aiHint: 'Alan ihtiyacı kişilikle ilgili, olgunlukla değil; kuralcı olmayı olumsuz çerçeveleme.',
    qualityNote:
      'Ev paylaşımı L2 derinliği: alan ve sınır ihtiyacını güvenli bir çerçevede yoklar.',
    answerWeights: {
      sessizlik: { 'alan-ihtiyaci': 1.5 },
      mutfak: { 'duzen-kaos': -1 },
      alan: { 'alan-ihtiyaci': 1.5, 'bagimsizlik-dengesi': 1 },
      spontan: { 'spontanlik': 0.5, 'alan-ihtiyaci': -0.5 },
    },
    status: 'active',
  },
  {
    slug: 'stres-kacisi',
    category: 'ev',
    subcategory: 'stres yönetimi',
    trait: 'enerji-kaynagi',
    level: 2,
    intensity: 2,
    type: 'choice',
    estSeconds: 12,
    sparkScore: 4,
    funScore: 4,
    prompt: 'Zor bir gün geçirdin, eve geldin. Otomatik pilotun seni nereye götürür?',
    options: [
      { id: 'yatak', label: 'Yatağa — uyku çözer, sabah başka gün' },
      { id: 'mutfak', label: 'Mutfağa — bir şeyler pişirmek beni indirir' },
      { id: 'ekran', label: 'Ekrana — beynimi kapatacak bir şey açarım, ne olduğu önemli değil' },
      { id: 'disari', label: 'Tekrar dışarı — yürüyüş, müzik, hareket' },
    ],
    shuffleOptions: true,
    followupPrompt:
      'Kötü gün ilacınız ne? Birbirinize reçete yazın.',
    qualityNote:
      'Stresle başa çıkma L2 konusu; ev sahnesiyle somutlaştırılmış, dört yol da sağlıklı.',
    answerWeights: {
      yatak: { 'alan-ihtiyaci': 1 },
      mutfak: { 'ritual-bagliligi': 0.5 },
      ekran: { 'alan-ihtiyaci': 0.5 },
      disari: { 'enerji-kaynagi': -0.5, 'ev-disari-dengesi': 1 },
    },
    status: 'active',
  },
  // Günlük Ritim (L2 derinlik)
  {
    slug: 'alarm-iliskisi',
    category: 'ritim',
    subcategory: 'sabah rutini',
    trait: 'sabah-gece-ritmi',
    level: 2,
    intensity: 1,
    type: 'either_or',
    estSeconds: 8,
    sparkScore: 3,
    funScore: 5,
    prompt: 'Sabah alarmınla ilişkin nasıl?',
    options: [
      { id: 'ilk', label: 'İlk alarm, hemen kalkarım — erteleyen kim?' },
      { id: 'ertele', label: 'Erteleme butonu benim en yakın arkadaşım; en az üç tur' },
    ],
    shuffleOptions: true,
    followupPrompt:
      'Sabahları kendinize kaç dakikada insan hissettirirsiniz? Dürüstlük turu.',
    qualityNote:
      'L1 hediye-saat sorusunun pratik günlük hâli; evrensel ve güldüren bir küçük itiraf.',
    answerWeights: {
      ilk: { 'sabah-gece-ritmi': -1, 'plan-sevgisi': 0.5 },
      ertele: { 'sabah-gece-ritmi': 1 },
    },
    status: 'active',
  },
  {
    slug: 'hafta-sonu-plani',
    category: 'ritim',
    subcategory: 'hafta sonu yönetimi',
    trait: 'plan-sevgisi',
    level: 2,
    intensity: 2,
    type: 'slider',
    estSeconds: 6,
    sparkScore: 4,
    funScore: 4,
    prompt: 'Hafta sonunu nasıl geçireceğin konusunda neredesin?',
    slider: {
      min: 1,
      max: 5,
      lowLabel: 'Cuma akşamı planım hazırdır; saati bile belli',
      highLabel: 'Cumartesi sabahı karar veririm; belki hiçbir şey yapmam',
    },
    shuffleOptions: false,
    followupPrompt:
      'Birlikte bir hafta sonu planlasanız: planı kim yapar, kim akışına bırakır?',
    qualityNote:
      'L1 boş-pazar sorusunun plan boyutuna odaklanan versiyonu; spektrum gerçek ve iki uç da cazip.',
    answerWeights: {
      low: { 'plan-sevgisi': 1.5 },
      mid: {},
      high: { 'plan-sevgisi': -1, 'spontanlik': 1 },
    },
    status: 'active',
  },
  {
    slug: 'gecikme-itirafi',
    category: 'ritim',
    subcategory: 'zaman yönetimi',
    trait: 'tempo',
    level: 2,
    intensity: 1,
    type: 'choice',
    estSeconds: 10,
    sparkScore: 4,
    funScore: 5,
    prompt: 'Bir buluşmaya gitme vaktin geldi. Sen büyük ihtimalle hangisisin?',
    options: [
      { id: 'erken', label: 'On dakika erken: kapıda beklerim, geç kalmaktansa' },
      { id: 'tam', label: 'Dakikasında: ne erken ne geç, bu bir sanattır' },
      { id: 'gec', label: '"Yoldayım" mesajını evden atıyorum — ve bunda pişmanlık yok' },
    ],
    shuffleOptions: true,
    followupPrompt:
      'En çok geç kaldığınız anınız: ne kadar geç, ne oldu sonra?',
    qualityNote:
      'Zaman yönetimi herkesin bildiği bir alışkanlık; üç seçenek de karakterli ve kimse "yanlış" değil.',
    answerWeights: {
      erken: { 'tempo': -0.5, 'plan-sevgisi': 0.5 },
      tam: { 'plan-sevgisi': 1 },
      gec: { 'tempo': 0.5, 'spontanlik': 0.5 },
    },
    status: 'active',
  },
  // Tat & Mutfak (L2 derinlik)
  {
    slug: 'yemek-yapma-hali',
    category: 'lezzet',
    subcategory: 'mutfak ilişkisi',
    trait: 'ritual-bagliligi',
    level: 2,
    intensity: 1,
    type: 'choice',
    estSeconds: 12,
    sparkScore: 4,
    funScore: 4,
    prompt: 'Mutfakla ilişkin hangisine en yakın?',
    options: [
      { id: 'sevgi', label: 'Mutfak sevgi dilidir; pişirdiğimi paylaşmak en büyük keyiflerimden' },
      { id: 'surec', label: 'Tarif takibi, malzeme ayarlama — sürecin kendisi meditasyon' },
      { id: 'hizli', label: 'Pratik olsun: makarna, tost, hayatta kal yemekleri' },
      { id: 'disari', label: 'Mutfağım sadece çay ocağı; gerisini dışarıya bırakıyorum' },
    ],
    shuffleOptions: true,
    followupPrompt:
      'Birbirinize en iyi yaptığınız yemeği ve en büyük mutfak felaketinizi anlatın.',
    qualityNote:
      'L1 lezzet sorularının davranış katmanı: yemek yapma-yapmama tercihi L2 derinliğinde kişilik yansıtır.',
    answerWeights: {
      sevgi: { 'paylasim-istahi': 1, 'ritual-bagliligi': 0.5 },
      surec: { 'ritual-bagliligi': 1.5 },
      hizli: { 'tempo': 1 },
      disari: { 'ev-disari-dengesi': 1 },
    },
    status: 'active',
  },
  {
    slug: 'yemek-macerasi',
    category: 'lezzet',
    subcategory: 'tat macerası',
    trait: 'merak-tarzi',
    level: 2,
    intensity: 2,
    type: 'slider',
    estSeconds: 6,
    sparkScore: 3,
    funScore: 4,
    prompt: 'Yeni ve yabancı tatlar konusunda neredesin?',
    slider: {
      min: 1,
      max: 5,
      lowLabel: 'Bildiklerim bana yeter; macera başka konularda',
      highLabel: 'Ne kadar tuhaf o kadar iyi; ismi garip olan tabağı isterim',
    },
    shuffleOptions: false,
    followupPrompt:
      'Şimdiye kadar denediğiniz en tuhaf yemeği anlatın. Tekrar yer miydiniz?',
    qualityNote:
      'L1 hep-aldigim-sey sorusunun slider formatında daha direkt versiyonu; farklı trait olmasa da merak tarzının başka yüzü.',
    answerWeights: {
      low: { 'merak-tarzi': -1, 'konfor-alani': 1 },
      mid: {},
      high: { 'merak-tarzi': 1.5, 'risk-istahi': 0.5 },
    },
    status: 'active',
  },
  {
    slug: 'kahvalti-ciddiyeti',
    category: 'lezzet',
    subcategory: 'günlük ritüel',
    trait: 'ritual-bagliligi',
    level: 2,
    intensity: 1,
    type: 'either_or',
    estSeconds: 8,
    sparkScore: 3,
    funScore: 4,
    prompt: 'Kahvaltı senin için ne?',
    options: [
      { id: 'kutsal', label: 'Günün en önemli anı — masası, düzeni, ritüeli var' },
      { id: 'atlanan', label: 'Kahve yeter; yemek öğlen başlar benim için' },
    ],
    shuffleOptions: true,
    followupPrompt:
      'Rüya kahvaltınızı tarif edin: nerede, ne var masada, yanınızda kim?',
    qualityNote:
      'Kahvaltı alışkanlığı L2 derinliğinde günlük ritüel ve yaşam temposunu yansıtır; klişeyi sahneyle aşar.',
    answerWeights: {
      kutsal: { 'ritual-bagliligi': 1.5, 'tempo': -0.5 },
      atlanan: { 'ritual-bagliligi': -1, 'tempo': 0.5 },
    },
    status: 'active',
  },
  // Seyahat & Keşif (L2 derinlik)
  {
    slug: 'kaybolma-refleksi',
    category: 'kesif',
    subcategory: 'keşif tarzı',
    trait: 'macera-istahi',
    level: 2,
    intensity: 2,
    type: 'either_or',
    estSeconds: 8,
    sparkScore: 5,
    funScore: 4,
    prompt: 'Yeni bir şehirdesin, Google Maps bitti. Ne yaparsın?',
    options: [
      { id: 'kaybol', label: 'Mükemmel — en iyi keşifler kaybolunca olur' },
      { id: 'sor', label: 'Birine sorarım; kaybolmak romantik değil, zaman kaybı' },
    ],
    shuffleOptions: true,
    followupPrompt:
      'Bir şehirde gerçekten kaybolduğunuz anı anlatın. Ne buldunuz?',
    aiHint: 'İki yaklaşım da geçerli; "cesaret" ve "korkaklık" çerçevesi kurma.',
    qualityNote:
      'L1 kesif sorularının pratik versiyonu: kaybolma refleksi macera iştahını doğrudan gösterir.',
    answerWeights: {
      kaybol: { 'macera-istahi': 1.5, 'spontanlik': 0.5 },
      sor: { 'macera-istahi': -0.5, 'plan-sevgisi': 0.5 },
    },
    status: 'active',
  },
  {
    slug: 'tatil-butcesi',
    category: 'kesif',
    subcategory: 'tatil harcaması',
    trait: 'oncelik-pusulasi',
    level: 2,
    intensity: 2,
    type: 'choice',
    estSeconds: 12,
    sparkScore: 4,
    funScore: 4,
    prompt: 'Tatilde paranın en çok nereye gittiğini düşünürsün?',
    options: [
      { id: 'konaklama', label: 'Güzel kalacak yer — uyku ve konfor tatili yapar' },
      { id: 'yemek', label: 'Yemek ve mekan — o şehrin tadını çıkarmak lazım' },
      { id: 'deneyim', label: 'Aktivite ve deneyimler — uyumaya vakit yok' },
      { id: 'hepsi', label: 'Ucuz kal, ucuz ye, parayı süreye yatır — daha uzun tatil' },
    ],
    shuffleOptions: true,
    followupPrompt:
      'Birlikte tatil planlasanız bütçeyi neye harcardınız? Üzerinde anlaşın.',
    qualityNote:
      'Keşif ve para kesişimi: tatil bütçe tercihi kişinin yolculukta neyi öncelediğini görünür kılar.',
    answerWeights: {
      konaklama: { 'konfor-alani': 1, 'oncelik-pusulasi': 0.5 },
      yemek: { 'merak-tarzi': 0.5 },
      deneyim: { 'macera-istahi': 1, 'oncelik-pusulasi': -0.5 },
      hepsi: { 'para-keyif-dengesi': 1, 'oncelik-pusulasi': -1 },
    },
    status: 'active',
  },
  {
    slug: 'rutin-bozma',
    category: 'kesif',
    subcategory: 'konfor alanı',
    trait: 'konfor-alani',
    level: 2,
    intensity: 2,
    type: 'slider',
    estSeconds: 6,
    sparkScore: 4,
    funScore: 3,
    prompt: 'Rutinini bozmak konusunda neredesin?',
    slider: {
      min: 1,
      max: 5,
      lowLabel: 'Rutinim beni tutar; bozarsam günüm kayar',
      highLabel: 'Aynı şeyi iki hafta yaparsam sıkılırım; değişiklik şart',
    },
    shuffleOptions: false,
    followupPrompt:
      'En son rutininizi kırdığınızda ne oldu? İyi mi bitti, kötü mü?',
    qualityNote:
      'L2 derinliğinde konfor alanı: rutine bağlılık spektrumu iki ucu da pozitif çerçeveler.',
    answerWeights: {
      low: { 'konfor-alani': 1.5, 'ritual-bagliligi': 1 },
      mid: {},
      high: { 'konfor-alani': -1.5, 'spontanlik': 0.5 },
    },
    status: 'active',
  },
  // Kültür & Eğlence (L2)
  {
    slug: 'oneri-direnci',
    category: 'kultur',
    subcategory: 'tavsiye alma',
    trait: 'konfor-alani',
    level: 2,
    intensity: 1,
    type: 'either_or',
    estSeconds: 8,
    sparkScore: 4,
    funScore: 4,
    prompt: 'Biri sana "şu diziyi kesinlikle izle" dedi. İlk refleksin?',
    options: [
      { id: 'hemen', label: 'Listeye eklenir, yakında izlerim — tavsiyeye açığım' },
      { id: 'ters', label: 'Bir tık geri çekilirim; herkes izle deyince izleyesim kaçar' },
    ],
    shuffleOptions: true,
    followupPrompt:
      'Tavsiye üzerine izleyip/okuyup/dinleyip aşık olduğunuz bir şey var mı? Ya da tam tersi?',
    qualityNote:
      'Kültür tüketimindeki bağımsızlık refleksi: "tavsiye direnci" tanıdık ve güldüren bir alışkanlık.',
    answerWeights: {
      hemen: { 'konfor-alani': -0.5, 'merak-tarzi': 0.5 },
      ters: { 'konfor-alani': 1 },
    },
    status: 'active',
  },
  {
    slug: 'tekrar-keyfi',
    category: 'kultur',
    subcategory: 'tekrar deneyimi',
    trait: 'nostalji-bagi',
    level: 2,
    intensity: 1,
    type: 'slider',
    estSeconds: 6,
    sparkScore: 3,
    funScore: 4,
    prompt: 'Aynı filmi, kitabı veya şarkıyı tekrar tekrar deneyimlemek konusunda neredesin?',
    slider: {
      min: 1,
      max: 5,
      lowLabel: 'İlk seferden sonra bitmiştir; yeni şeyler bekliyor',
      highLabel: 'En iyi şeyler tekrarla güzelleşir; her seferinde yeni bir şey bulurum',
    },
    shuffleOptions: false,
    followupPrompt:
      'En çok tekrar ettiğiniz şeyi söyleyin: film, şarkı, kitap, ne olursa. Kaç kez?',
    qualityNote:
      'L1 ezber-film sorusunun slider formatında genişletilmiş hâli; farklı içerik türlerini kapsar.',
    answerWeights: {
      low: { 'nostalji-bagi': -1, 'merak-tarzi': 0.5 },
      mid: {},
      high: { 'nostalji-bagi': 1.5, 'konfor-alani': 0.5 },
    },
    status: 'active',
  },
  // Nostalji (L2)
  {
    slug: 'cocukluk-kahramani',
    category: 'nostalji',
    subcategory: 'ilk etkiler',
    trait: 'nostalji-bagi',
    level: 2,
    intensity: 2,
    type: 'choice',
    estSeconds: 15,
    sparkScore: 4,
    funScore: 4,
    prompt: 'Çocukken en çok etkilendiğin karakter nereden geliyordu?',
    options: [
      { id: 'cizgi', label: 'Çizgi film / anime — o dünya gerçeğinden iyiydi' },
      { id: 'kitap', label: 'Bir kitap veya hikâye — hayal gücüm orada açıldı' },
      { id: 'gercek', label: 'Gerçek bir insan — aile, öğretmen, sporcu' },
      { id: 'oyun', label: 'Bir oyundaki karakter — kontrol bende olunca daha derindi' },
    ],
    shuffleOptions: true,
    followupPrompt:
      'O karakterin/kişinin size bıraktığı en büyük iz ne? Birbirinize anlatın.',
    qualityNote:
      'Çocukluk kahramanı L2 derinliğinde nostalji + değer yoklama: cevap hem anı hem karakter yansıtır.',
    answerWeights: {
      cizgi: { 'nostalji-bagi': 1 },
      kitap: { 'nostalji-bagi': 1, 'merak-tarzi': 0.5 },
      gercek: { 'nostalji-bagi': 0.5 },
      oyun: { 'nostalji-bagi': 0.5 },
    },
    status: 'active',
  },
  // Hayaller & Olasılıklar (L2)
  {
    slug: 'paralel-hayat',
    category: 'hayal',
    subcategory: 'alternatif benlik',
    trait: 'oncelik-pusulasi',
    level: 2,
    intensity: 2,
    type: 'choice',
    estSeconds: 15,
    sparkScore: 5,
    funScore: 5,
    prompt:
      'Paralel bir evrende bambaşka bir hayat yaşıyorsun. Hangisi olsa "aa, o da bendim ha" derdin?',
    options: [
      { id: 'sanatci', label: 'Küçük bir kasabada atölye açmış bir sanatçı' },
      { id: 'gezgin', label: 'Sırt çantalı, evden eve sürüklenen bir gezgin' },
      { id: 'akademik', label: 'Bir üniversitede tuhaf bir konu araştıran akademisyen' },
      { id: 'isletme', label: 'Kendi küçük işletmesini kurmuş, rutini olan biri' },
    ],
    shuffleOptions: true,
    followupPrompt:
      'Paralel hayatınızın bir gününü detaylıca anlatın. Sabahtan akşama ne yapıyorsunuz?',
    qualityNote:
      'L1 bir-gunluk-hayat sorusunun L2 versiyonu: daha kalıcı bir hayat hayal ettirerek değer ve öncelik yansıtır.',
    answerWeights: {
      sanatci: { 'oncelik-pusulasi': 1, 'tempo': -0.5 },
      gezgin: { 'macera-istahi': 1.5, 'koklenme-gocebelik': 1 },
      akademik: { 'merak-tarzi': 1, 'oncelik-pusulasi': 0.5 },
      isletme: { 'oncelik-pusulasi': -0.5, 'koklenme-gocebelik': -1 },
    },
    status: 'active',
  },
  // Küçük İtiraflar (L2)
  {
    slug: 'erteleme-sanati',
    category: 'itiraf',
    subcategory: 'erteleme alışkanlığı',
    trait: 'tempo',
    level: 2,
    intensity: 1,
    type: 'either_or',
    estSeconds: 8,
    sparkScore: 3,
    funScore: 5,
    prompt: 'Yapılacaklar listende bir şey var, son gün yarın. Sen hangisisin?',
    options: [
      { id: 'erken', label: 'Çoktan bitti; son güne bırakmak bana stres verir' },
      { id: 'son-gece', label: 'Son gece mucizesi — baskı altında parlıyorum' },
    ],
    shuffleOptions: true,
    followupPrompt:
      'Ertelemenin sizi en çok kurtardığı veya en çok batırdığı anı anlatın.',
    qualityNote:
      'Evrensel bir küçük itiraf; her iki taraf da övünülebilir şekilde yazılmış, L2 derinliğinde zaman yönetimini yoklar.',
    answerWeights: {
      erken: { 'plan-sevgisi': 1, 'tempo': -0.5 },
      'son-gece': { 'spontanlik': 0.5, 'risk-istahi': 0.5 },
    },
    status: 'active',
  },
  // İletişim & Duygular (L2)
  {
    slug: 'heyecan-paylasma',
    category: 'iletisim',
    subcategory: 'ifade tarzı',
    trait: 'ifade-tarzi',
    level: 2,
    intensity: 2,
    type: 'slider',
    estSeconds: 6,
    sparkScore: 4,
    funScore: 3,
    prompt: 'Bir şeyi çok sevdiğinde bunu gösterme tarzın nereye yakın?',
    slider: {
      min: 1,
      max: 5,
      lowLabel: 'Sessizce sahiplenirim; detayları sonra açılır',
      highLabel: 'Hemen anlatırım; heyecanım odada dolaşır',
    },
    shuffleOptions: false,
    followupPrompt:
      'Son zamanlarda sizi heyecanlandıran bir şeyi anlatın; nasıl anlattığınıza da bakın.',
    qualityNote:
      'Duygu ifadesini güvenli ve olumlu bir sahneyle yoklar; ilişki konuşması değil, heyecan paylaşma biçimi.',
    answerWeights: {
      low: { 'ifade-tarzi': 1, 'paylasim-istahi': -1 },
      mid: {},
      high: { 'ifade-tarzi': -1.5, 'paylasim-istahi': 1.5 },
    },
    status: 'active',
  },
  // ── Havuz genişletme: 12 yeni L2 sorusu ──
  {
    slug: 'tatil-donusu',
    category: 'kesif',
    subcategory: 'seyahat dönüşü',
    trait: 'nostalji-bagi',
    level: 2,
    intensity: 2,
    type: 'choice',
    estSeconds: 10,
    sparkScore: 4,
    funScore: 4,
    prompt: 'Tatilden döndüğünde ilk ne yaparsın?',
    options: [
      { id: 'yerlestir', label: 'Hemen bavulu açar, her şeyi yerine koyarım' },
      { id: 'koltuk', label: 'Bavul günlerce öyle kalır, ben koltuğa gömülürüm' },
      { id: 'fotograf', label: 'Fotoğraflara bakarım, hemen paylaşırım' },
      { id: 'plan', label: 'Sonraki tatili düşünmeye başlarım' },
    ],
    shuffleOptions: true,
    followupPrompt: 'Tatil sonrası ritüelleriniz nasıl farklı?',
    qualityNote: 'Nostalji, düzen ve planlama ayrımı.',
    answerWeights: {
      yerlestir: { 'duzen-kaos': -1, 'plan-sevgisi': 0.5 },
      koltuk: { tempo: -1 },
      fotograf: { 'paylasim-istahi': 1.5, 'nostalji-bagi': 0.5 },
      plan: { 'macera-istahi': 1, 'nostalji-bagi': -0.5 },
    },
    status: 'active',
  },
  {
    slug: 'arkadas-sikayeti',
    category: 'iletisim',
    subcategory: 'destek tarzı',
    trait: 'ifade-tarzi',
    level: 2,
    intensity: 2,
    type: 'choice',
    estSeconds: 10,
    sparkScore: 4,
    funScore: 3,
    prompt: 'Yakın arkadaşın biriyle ilgili şikâyet ediyor. Sen ne yaparsın?',
    options: [
      { id: 'dinle', label: 'Sadece dinlerim, onu anlamaya çalışırım' },
      { id: 'cozum', label: 'Hemen çözüm önermeye başlarım' },
      { id: 'soru', label: 'Sorular sorarım — belki farklı açıdan bakması gerekir' },
      { id: 'destek', label: 'Onun tarafını tutarım, haklısın derim' },
    ],
    shuffleOptions: true,
    followupPrompt: 'Birisi dert anlatırken ikiniz de aynı tepkiyi mi veriyorsunuz?',
    qualityNote: 'Dinleme derinliği ve ifade tarzı ayrımı.',
    answerWeights: {
      dinle: { 'ifade-tarzi': 1, 'alan-ihtiyaci': -0.5 },
      cozum: { 'ifade-tarzi': -1 },
      soru: { 'merak-tarzi': 0.5 },
      destek: { 'paylasim-istahi': 0.5 },
    },
    status: 'active',
  },
  {
    slug: 'ev-dekor',
    category: 'ev',
    subcategory: 'estetik',
    trait: 'duzen-kaos',
    level: 2,
    intensity: 1,
    type: 'either_or',
    estSeconds: 8,
    sparkScore: 3,
    funScore: 4,
    prompt: 'Evin dekoru konusunda hangisi sana daha yakın?',
    options: [
      { id: 'minimal', label: 'Az eşya, çok boşluk — minimalizm' },
      { id: 'dolu', label: 'Her köşede bir anı, raflar dolu — sıcak kaos' },
    ],
    shuffleOptions: true,
    followupPrompt: 'İdeal yaşam alanınız nasıl görünür?',
    qualityNote: 'Düzen vs sıcaklık tercihi.',
    answerWeights: {
      minimal: { 'duzen-kaos': -1.5 },
      dolu: { 'duzen-kaos': 1, 'nostalji-bagi': 0.5 },
    },
    status: 'active',
  },
  {
    slug: 'muzik-kesfetme',
    category: 'kultur',
    subcategory: 'müzik',
    trait: 'merak-tarzi',
    level: 2,
    intensity: 1,
    type: 'choice',
    estSeconds: 10,
    sparkScore: 4,
    funScore: 5,
    prompt: 'Yeni müzik nasıl keşfedersin?',
    options: [
      { id: 'algoritma', label: 'Algoritma önerir, güvenirim' },
      { id: 'arkadas', label: 'Arkadaş tavsiyesi — biri gönderirse dinlerim' },
      { id: 'kazirim', label: 'Saatlerce kazarım — Spotify\'ın diplerine inerim' },
      { id: 'kesfetmem', label: 'Pek keşfetmem, bildiklerimi dinlerim' },
    ],
    shuffleOptions: true,
    followupPrompt: 'Son keşfettiğiniz bir şarkıyı birbirinize gönderin.',
    qualityNote: 'Merak tarzı ve konfor alanı ayrımı.',
    answerWeights: {
      algoritma: {},
      arkadas: { 'paylasim-istahi': 0.5 },
      kazirim: { 'merak-tarzi': -1.5 },
      kesfetmem: { 'konfor-alani': 1, 'merak-tarzi': 1 },
    },
    status: 'active',
  },
  {
    slug: 'hediye-almak',
    category: 'sosyal',
    subcategory: 'hediye',
    trait: 'paylasim-istahi',
    level: 2,
    intensity: 1,
    type: 'either_or',
    estSeconds: 8,
    sparkScore: 3,
    funScore: 4,
    prompt: 'Hediye alırken daha çok hangisi?',
    options: [
      { id: 'arar', label: 'Haftalarca düşünürüm — mükemmel hediyeyi bulurum' },
      { id: 'anlik', label: 'Bir şey görürüm, "buna bayılır" derim, alırım' },
    ],
    shuffleOptions: true,
    followupPrompt: 'Size gelen en güzel hediye neydi?',
    qualityNote: 'Plan sevgisi ve spontanlık kesişimi.',
    answerWeights: {
      arar: { 'plan-sevgisi': 1, 'paylasim-istahi': 0.5 },
      anlik: { spontanlik: 1, 'paylasim-istahi': 0.5 },
    },
    status: 'active',
  },
  {
    slug: 'sessiz-ortam',
    category: 'ritim',
    subcategory: 'enerji',
    trait: 'enerji-kaynagi',
    level: 2,
    intensity: 2,
    type: 'slider',
    estSeconds: 10,
    sparkScore: 3,
    funScore: 3,
    prompt: 'Kalabalık bir yerde uzun süre kaldıktan sonra kendine gelme süren?',
    slider: {
      lowLabel: 'Hemen toplarım, sorun değil',
      highLabel: 'Yarın gün bana lazım, kimseyle konuşmam',
      midLabel: 'Birkaç saat yeter',
    },
    shuffleOptions: false,
    followupPrompt: 'Sosyal etkinlik sonrası şarj olma süreniz uyuşuyor mu?',
    qualityNote: 'Sosyal enerji tükenme hızı.',
    answerWeights: {
      low: { 'enerji-kaynagi': -1.5 },
      mid: {},
      high: { 'enerji-kaynagi': 1.5, 'alan-ihtiyaci': 1 },
    },
    status: 'active',
  },
  {
    slug: 'para-konusu',
    category: 'para',
    subcategory: 'paylaşım',
    trait: 'para-keyif-dengesi',
    level: 2,
    intensity: 2,
    type: 'choice',
    estSeconds: 10,
    sparkScore: 4,
    funScore: 3,
    prompt: 'Arkadaş grubunda biri her zaman hesabı bölmek istemezse ne düşünürsün?',
    options: [
      { id: 'sorun', label: 'Rahatsız olurum ama söylemem' },
      { id: 'soyle', label: 'Kibarca belirtirim' },
      { id: 'farketmez', label: 'Umursamam, keyif bozmasın' },
      { id: 'ogle', label: 'Duruma göre değişir, bağlama bakarım' },
    ],
    shuffleOptions: true,
    followupPrompt: 'Para konuşmak sizin için ne kadar rahat?',
    qualityNote: 'Para ve iletişim tarzı kesişimi.',
    answerWeights: {
      sorun: { 'ifade-tarzi': 1, 'para-keyif-dengesi': 1 },
      soyle: { 'ifade-tarzi': -1 },
      farketmez: { 'para-keyif-dengesi': -0.5 },
      ogle: {},
    },
    status: 'active',
  },
  {
    slug: 'uzun-mesaj',
    category: 'iletisim',
    subcategory: 'mesajlaşma',
    trait: 'temas-ritmi',
    level: 2,
    intensity: 2,
    type: 'either_or',
    estSeconds: 8,
    sparkScore: 4,
    funScore: 4,
    prompt: 'Mesajlaşma tarzın?',
    options: [
      { id: 'uzun', label: 'Uzun paragraflar — her şeyi bir mesajda anlatırım' },
      { id: 'kisa', label: 'Kısa kısa — her cümle ayrı mesaj' },
    ],
    shuffleOptions: true,
    followupPrompt: 'Mesajlaşma tarzlarınız uyuşuyor mu?',
    qualityNote: 'İletişim tercihi, ilişki dinamiği.',
    answerWeights: {
      uzun: { 'temas-ritmi': -0.5, 'ifade-tarzi': -1 },
      kisa: { 'temas-ritmi': 0.5, tempo: 0.5 },
    },
    status: 'active',
  },
  {
    slug: 'yemek-deneme',
    category: 'lezzet',
    subcategory: 'deneme',
    trait: 'risk-istahi',
    level: 2,
    intensity: 1,
    type: 'choice',
    estSeconds: 10,
    sparkScore: 3,
    funScore: 5,
    prompt: 'Menüde hiç bilmediğin bir yemek var. Ne yaparsın?',
    options: [
      { id: 'dene', label: 'Kesinlikle denerim — bilmediğim şeyleri severim' },
      { id: 'sor', label: 'Garsona sorarım, detay alırım, sonra karar veririm' },
      { id: 'bilinen', label: 'Güvenli olanı seçerim, macera istemem' },
      { id: 'paylas', label: 'Biri denemeli ki tadına bakayım' },
    ],
    shuffleOptions: true,
    followupPrompt: 'Yemek konusunda ne kadar maceraperestsiniz?',
    qualityNote: 'Yemek üzerinden risk ve merak.',
    answerWeights: {
      dene: { 'risk-istahi': 1.5, 'merak-tarzi': 0.5 },
      sor: { 'plan-sevgisi': 0.5 },
      bilinen: { 'konfor-alani': 1.5, 'risk-istahi': -1 },
      paylas: { 'risk-istahi': 0.5 },
    },
    status: 'active',
  },
  {
    slug: 'nostalji-esya',
    category: 'nostalji',
    subcategory: 'anı',
    trait: 'nostalji-bagi',
    level: 2,
    intensity: 1,
    type: 'either_or',
    estSeconds: 8,
    sparkScore: 4,
    funScore: 4,
    prompt: 'Eski eşyalarını atabilir misin?',
    options: [
      { id: 'atamam', label: 'Atamam — her birinin bir hikâyesi var' },
      { id: 'rahat', label: 'Rahat atarım — yer açılsın' },
    ],
    shuffleOptions: true,
    followupPrompt: 'En uzun süredir sakladığınız eşya ne?',
    qualityNote: 'Nostalji bağı somut bir soru.',
    answerWeights: {
      atamam: { 'nostalji-bagi': 1.5, 'duzen-kaos': 0.5 },
      rahat: { 'nostalji-bagi': -1.5, 'duzen-kaos': -0.5 },
    },
    status: 'active',
  },
  {
    slug: 'grup-karar',
    category: 'sosyal',
    subcategory: 'grup dinamiği',
    trait: 'grup-rolu',
    level: 2,
    intensity: 2,
    type: 'choice',
    estSeconds: 10,
    sparkScore: 3,
    funScore: 4,
    prompt: 'Arkadaş grubunda plan yapılırken sen genelde ne roldesin?',
    options: [
      { id: 'kurucu', label: 'Planı kuran benim — tarih, yer, saat' },
      { id: 'fikir', label: 'Fikir atarım ama organizasyon başkasında' },
      { id: 'katilimci', label: '"Nereye gidersek gideriz" tayfasıyım' },
      { id: 'motive', label: 'Herkesi motive eden benim — "hadi yapılsın artık"' },
    ],
    shuffleOptions: true,
    followupPrompt: 'Sosyal planlamada rolleriniz tamamlayıcı mı?',
    qualityNote: 'Grup rolü tekrarı güçlü sinyal.',
    answerWeights: {
      kurucu: { 'grup-rolu': -1.5, 'plan-sevgisi': 0.5 },
      fikir: { 'grup-rolu': -0.5 },
      katilimci: { 'grup-rolu': 1.5 },
      motive: { 'grup-rolu': 0.5, 'enerji-kaynagi': -0.5 },
    },
    status: 'active',
  },
  {
    slug: 'hayal-mekan',
    category: 'hayal',
    subcategory: 'yaşam hayali',
    trait: 'koklenme-gocebelik',
    level: 2,
    intensity: 1,
    type: 'choice',
    estSeconds: 10,
    sparkScore: 5,
    funScore: 5,
    prompt: 'Sınırsız imkânın olsa nerede yaşamak isterdin?',
    options: [
      { id: 'deniz', label: 'Deniz kenarı küçük bir kasaba' },
      { id: 'sehir', label: 'Büyük bir şehrin kalbinde' },
      { id: 'dag', label: 'Dağ başında sessiz bir ev' },
      { id: 'gezgin', label: 'Sabit bir yer değil — sürekli farklı şehirler' },
    ],
    shuffleOptions: true,
    followupPrompt: 'İdeal yaşam hayaliniz örtüşüyor mu?',
    qualityNote: 'Köklenme vs göçebelik, sohbet açıcı.',
    answerWeights: {
      deniz: { 'koklenme-gocebelik': -1, tempo: -0.5 },
      sehir: { 'koklenme-gocebelik': -0.5, 'enerji-kaynagi': -0.5 },
      dag: { 'koklenme-gocebelik': -1.5, 'alan-ihtiyaci': 1 },
      gezgin: { 'koklenme-gocebelik': 1.5, 'macera-istahi': 1 },
    },
    status: 'active',
  },
]
