import type { QuestionContent } from '../types'

// Seviye 1 (İlk Tanışma) havuzu — ilk parti, 24 soru.
// İçerik onayı: docs/product/QUESTIONS_LEVEL1.md (Aşama 3).
// Parti kısıtları: kategori başına ≤3, trait başına ≤2,
// 8 ikilem / 10 çoktan seçmeli / 6 slider.
export const level1Questions: QuestionContent[] = [
  // Tat & Mutfak
  {
    slug: 'hep-aldigim-sey',
    category: 'lezzet',
    subcategory: 'restoran ritüelleri',
    trait: 'merak-tarzi',
    level: 1,
    intensity: 1,
    type: 'either_or',
    estSeconds: 8,
    sparkScore: 4,
    funScore: 4,
    prompt:
      'Çok sevdiğin bir mekândasın. Menüde hiç denemediğin ama kulağa harika gelen bir şey var. Ne yaparsın?',
    options: [
      { id: 'klasik', label: 'Riske girmem — hep aldığımı alırım, zaten o yüzden seviyorum burayı' },
      { id: 'yeni', label: 'Yeni olan neyse o — en kötü senin tabağından alırım' },
    ],
    shuffleOptions: true,
    followupPrompt:
      'Birbirinize "değişmez siparişim" dediğiniz klasiği ve onu ilk keşfettiğiniz anı anlatın.',
    qualityNote:
      'Merak tarzını sıfatla değil sahneyle yoklar; iki cevap da savunulabilir. "Senin tabağından alırım" iki kişilik bağlama göz kırpar.',
    status: 'active',
  },
  {
    slug: 'gece-mutfagi',
    category: 'lezzet',
    subcategory: 'gece atıştırması',
    trait: 'ritual-bagliligi',
    level: 1,
    intensity: 1,
    type: 'choice',
    estSeconds: 10,
    sparkScore: 3,
    funScore: 5,
    prompt: 'Gece yarısı, herkes uyuyor, mutfağa süzüldün. Elinde büyük ihtimalle ne var?',
    options: [
      { id: 'dolap', label: 'Dolapta ne bulursam — soğuk soğuk, gerekirse tencereden' },
      { id: 'tatli', label: 'Tatlı bir şeyler; çikolata radarım gece de kapanmaz' },
      { id: 'sandvic', label: 'Ciddi iş: kendime düzgün bir sandviç kuruyorum' },
      { id: 'su', label: 'Ben sadece su almaya inmiştim, yemin ederim' },
    ],
    // Son seçenek espri olarak en sonda çalışır; sıra sabit kalır.
    shuffleOptions: false,
    followupPrompt:
      'Gece mutfağının en garip eserini itiraf etme turu: en tuhaf gece atıştırması hanginizde?',
    qualityNote:
      'Evrensel ve suçsuz bir küçük itiraf sahnesi; her seçenek mini bir karakter vinyeti, dördüncüsü kaçış değil espri.',
    status: 'active',
  },
  {
    slug: 'catal-diplomasisi',
    category: 'lezzet',
    subcategory: 'masa kültürü',
    trait: 'paylasim-istahi',
    level: 1,
    intensity: 1,
    type: 'slider',
    estSeconds: 6,
    sparkScore: 4,
    funScore: 5,
    prompt: 'Masada yemek paylaşımı konusunda neredesin?',
    slider: {
      min: 1,
      max: 5,
      lowLabel: 'Tabağım kalemdir, sınırdır',
      highLabel: 'Masadaki her şey ortaktır, çatalım gezer',
    },
    shuffleOptions: false,
    followupPrompt:
      'Masada tabak paylaşımının kuralları ne olmalı? İkiniz bir "çatal anayasası" yazın.',
    qualityNote:
      'İki uç da pozitif ve sahiplenilebilir; gerçek bir spektrum. Buluşma masasında sorulunca o masayı sohbet konusu yapar.',
    status: 'active',
  },
  // Seyahat & Keşif
  {
    slug: 'gece-yolculugu-teklifi',
    category: 'kesif',
    subcategory: 'spontane plan',
    trait: 'spontanlik',
    level: 1,
    intensity: 1,
    type: 'either_or',
    estSeconds: 8,
    sparkScore: 5,
    funScore: 4,
    prompt:
      'Arkadaşın gece 22.00’de aradı: "Hadi şimdi yola çıkalım, sabah deniz kenarındayız." İlk tepkin?',
    options: [
      { id: 'hemen', label: 'Çantam beş dakikada hazır, yoldan mesaj atarım' },
      { id: 'planla', label: 'Harika fikir — hafta sonu için planlayalım, düzgün yapalım' },
    ],
    shuffleOptions: true,
    followupPrompt:
      'Hiç plansız çıkılmış bir yolculuğunuz oldu mu? En iyisini ya da en felaket olanını anlatın.',
    aiHint:
      'İki cevap da maceraya açık; fark sadece zamanlamada. "Biri cesur, biri temkinli" çerçevesi kurma.',
    qualityNote:
      'Spontanlığı etiketle değil sahneyle yoklar; "hayır" seçeneği bile iyi planlanmış bir macera olarak yazıldı.',
    status: 'active',
  },
  {
    slug: 'tatil-aksami-testi',
    category: 'kesif',
    subcategory: 'tatil ritmi',
    trait: 'plan-sevgisi',
    level: 1,
    intensity: 1,
    type: 'choice',
    estSeconds: 12,
    sparkScore: 4,
    funScore: 4,
    prompt:
      'Tatildesin ve bugün tamamen senin. Akşam olduğunda "harika bir gündü" dedirtecek olan hangisi?',
    options: [
      { id: 'rota', label: 'Haritada yıldızladığım yerlerin hepsini gezmiş olmak' },
      { id: 'kayip', label: 'Plansız sokaklarda kaybolup beklenmedik bir şey keşfetmiş olmak' },
      { id: 'sifir-acele', label: 'Manzara karşısında kitap, uyku ve sıfır acele' },
      { id: 'yerel', label: 'Yerel pazardan garip şeyler alıp bir günlüğüne oralı gibi yaşamak' },
    ],
    shuffleOptions: true,
    followupPrompt:
      'Bu dört akşamdan hangisi hayalinizdeki rotada olurdu? Bir sonraki tatil gününü birlikte kurgulayın.',
    qualityNote:
      'Anket sorusunu akşam muhasebesi sahnesine çevirir; dört seçenek dört farklı zevk, hiçbiri "doğru turist" değil.',
    status: 'active',
  },
  {
    slug: 'valiz-zamani',
    category: 'kesif',
    subcategory: 'yolculuk hazırlığı',
    trait: 'plan-sevgisi',
    level: 1,
    intensity: 1,
    type: 'slider',
    estSeconds: 6,
    sparkScore: 3,
    funScore: 4,
    prompt: 'Yolculuğa bir hafta var. Valiz cephesinde durum ne?',
    slider: {
      min: 1,
      max: 5,
      lowLabel: 'Valiz çoktan hazır, listem de var',
      highLabel: 'Valiz mi? Çıkarken bir çanta doldururum',
    },
    shuffleOptions: false,
    followupPrompt: 'Valizde asla eksik olmayan tuhaf eşyanız ne? İkiniz de birer tane söyleyin.',
    qualityNote:
      'İki uç da karakterli ve övünülebilir; sayı yok, orta nokta ("çoğu hazır, son gece panik") meşru bir konum.',
    status: 'active',
  },
  // Kültür & Eğlence
  {
    slug: 'ezber-film',
    category: 'kultur',
    subcategory: 'izleme alışkanlığı',
    trait: 'konfor-alani',
    level: 1,
    intensity: 1,
    type: 'either_or',
    estSeconds: 8,
    sparkScore: 4,
    funScore: 4,
    prompt: 'Boş bir akşam, bir şey açacaksın. Hangisi daha çok çekiyor?',
    options: [
      {
        id: 'ezber',
        label: 'Yüz kere izlediğim, repliklerini ezbere bildiğim filmim — o bir sarılma gibi',
      },
      {
        id: 'yeni',
        label: 'Hiç izlemediğim bir şey — aynı filmi ikinci kez izlemek bana israf gibi geliyor',
      },
    ],
    shuffleOptions: true,
    followupPrompt:
      'Replikleri ezbere bildiğiniz o yapımı söyleyin — ve neden hiç eskimediğini savunun.',
    qualityNote:
      'Liste sorusu yerine izleme davranışını sorar; "sarılma gibi" ve "israf gibi" ifadeleri iki tarafı duygusal olarak eşitler.',
    status: 'active',
  },
  {
    slug: 'yeni-sarki-refleksi',
    category: 'kultur',
    subcategory: 'müzik davranışı',
    trait: 'paylasim-istahi',
    level: 1,
    intensity: 1,
    type: 'choice',
    estSeconds: 12,
    sparkScore: 4,
    funScore: 4,
    prompt: 'Çok sevdiğin yeni bir şarkı keşfettin. Büyük ihtimalle sonra ne olur?',
    options: [
      { id: 'tuket', label: 'Tükenene kadar üst üste dinlerim, sonra bir süre küsüşürüz' },
      { id: 'gonder', label: 'Anında birine gönderirim — güzel şey paylaşınca güzel' },
      { id: 'sakla', label: 'Sessizce kendi listeme eklerim; o artık benim sırrım' },
      { id: 'arsiv', label: 'Sanatçının bütün arşivine dalarım, gece orada biter' },
    ],
    shuffleOptions: true,
    followupPrompt:
      'Birbirinize "bunu keşfettiğimde kimseye söylemedim" dediğiniz bir şarkı gönderin.',
    qualityNote:
      'Zevk değil davranış sorusu; "ne dinlersin?" performans baskısını atlar. Farklı cevaplar "bana da gönderir misin?" kapısını açar.',
    status: 'active',
  },
  // Nostalji & Çocukluk
  {
    slug: 'yaz-tatili-karesi',
    category: 'nostalji',
    subcategory: 'çocukluk yazları',
    trait: 'nostalji-bagi',
    level: 1,
    intensity: 1,
    type: 'choice',
    estSeconds: 12,
    sparkScore: 4,
    funScore: 5,
    prompt: 'Çocukluğundaki yaz tatillerini düşün. Aklına ilk gelen kare hangisine daha yakın?',
    options: [
      { id: 'memleket', label: 'Memleket, akraba kalabalığı, kuzenler ordusu' },
      { id: 'mahalle', label: 'Mahalle: akşam karanlığına kadar sokak, "eve gel" seslenişleri' },
      { id: 'deniz', label: 'Deniz, güneş kremi kokusu, ıslak havlu' },
      { id: 'ev', label: 'Serin ev hâli: çizgi filmler, kitaplar, uzun öğle uykuları' },
    ],
    shuffleOptions: true,
    followupPrompt:
      'Gözünüzü kapatın: çocukluk yazlarından tek bir koku ya da ses seçin, birbirinize anlatın.',
    qualityNote:
      'Hatırlama anının kendisi keyifli; seçenekler etiket değil görüntü ve koku üzerinden yazıldı, cevap otomatik anı anlattırır.',
    status: 'active',
  },
  {
    slug: 'ilk-harclik',
    category: 'nostalji',
    subcategory: 'ilk’ler',
    trait: 'para-keyif-dengesi',
    level: 1,
    intensity: 1,
    type: 'either_or',
    estSeconds: 8,
    sparkScore: 3,
    funScore: 4,
    prompt:
      'Çocukluğuna dön: eline ilk kez gerçekten "senin" olan bir para geçti. Sen hangi çocuktun?',
    options: [
      { id: 'harcadi', label: 'O para akşama yoktu — neye gittiğini sorma, hatırlamıyorum' },
      { id: 'biriktirdi', label: 'Kumbara müdürü — biriktirmenin kendisi ayrı bir oyundu' },
    ],
    shuffleOptions: true,
    followupPrompt: 'İlk "kendi paranızla" aldığınız şeyi hatırlıyor musunuz? İkiniz de anlatın.',
    aiHint:
      'Bu çocukluk anısıdır, bugünün finansal profili değil; yetişkin para yorumu yapma.',
    qualityNote:
      'Para eğilimini yetişkin finansı sormadan çocukluk sahnesine indirir: güvenli, tatlı, yine de kalıcı bir eğilimin ilk fotoğrafı.',
    status: 'active',
  },
  {
    slug: 'gecmisle-aran',
    category: 'nostalji',
    subcategory: 'geçmişle ilişki',
    trait: 'nostalji-bagi',
    level: 1,
    intensity: 2,
    type: 'slider',
    estSeconds: 8,
    sparkScore: 3,
    funScore: 3,
    prompt: 'Geçmişle aran nasıl?',
    slider: {
      min: 1,
      max: 5,
      lowLabel: 'Eski fotoğraflar, eski şarkılar — arada oraya taşınırım',
      highLabel: 'Güzeldi, bitti; ben hep sıradakine bakarım',
    },
    shuffleOptions: false,
    followupPrompt: 'Dönüp dönüp baktığınız bir fotoğraf ya da şarkı var mı? Neden o?',
    aiHint: 'İki uç da romantize edilebilir: duygusal derinlik vs ileri bakış. Birini olgun gösterme.',
    qualityNote:
      'Gerçek bir spektrum; setin en düşündüren sorusu olarak zorluk 2, eğride ortalarda durmalı.',
    status: 'active',
  },
  // Günlük Ritim
  {
    slug: 'hediye-saat',
    category: 'ritim',
    subcategory: 'sabah/gece',
    trait: 'sabah-gece-ritmi',
    level: 1,
    intensity: 1,
    type: 'either_or',
    estSeconds: 8,
    sparkScore: 4,
    funScore: 4,
    prompt:
      'Dünya sana günde bir saat hediye etti: herkes uyurken sen uyanıksın. Bu saati günün hangi ucuna eklersin?',
    options: [
      { id: 'sabah', label: 'Sabaha — gün doğarken dünya sadece benimken' },
      { id: 'gece', label: 'Geceye — herkes susunca asıl ben başlarım' },
    ],
    shuffleOptions: true,
    followupPrompt:
      'O hediye saatte tam olarak ne yapardınız? Sabahçı ve gececi birbirine kendi saatini anlatsın.',
    qualityNote:
      'Klişe "sabah insanı mısın?" sorusunun hediye-saat fantezisiyle bükülmüş hâli; iki uç da imrenilecek bir sahne.',
    status: 'active',
  },
  {
    slug: 'bos-pazar',
    category: 'ritim',
    subcategory: 'hafta sonu',
    trait: 'ev-disari-dengesi',
    level: 1,
    intensity: 1,
    type: 'choice',
    estSeconds: 12,
    sparkScore: 4,
    funScore: 4,
    prompt: 'Pazar sabahı uyandın, gün tamamen boş. İçinden ilk gelen ne?',
    options: [
      { id: 'kahvalti', label: 'Kahvaltıyı ciddiye alıp günü ağırdan açmak' },
      { id: 'disari', label: 'Dışarı — boş gün, şehrin benim olduğu gün demek' },
      { id: 'topla', label: 'Bir plan uydurup birilerini toplamak; boş gün ziyan edilmez' },
      { id: 'koltuk', label: 'Boş gün kutsaldır: pijama, koltuk, "bir bölüm daha"' },
    ],
    shuffleOptions: true,
    followupPrompt: 'En son "mükemmel geçti" dediğiniz boş gün nasıldı? Detaylarıyla anlatın.',
    qualityNote:
      'Rehberdeki örnek sahnenin havuz hâli; dört meşru pazar, "tembel pazar" bile kutsal diye çerçevelenerek eşit prestije çekildi.',
    status: 'active',
  },
  {
    slug: 'hayat-temposu',
    category: 'ritim',
    subcategory: 'tempo',
    trait: 'tempo',
    level: 1,
    intensity: 1,
    type: 'slider',
    estSeconds: 6,
    sparkScore: 3,
    funScore: 4,
    prompt: 'Genel yaşam tempon hangi uca yakın?',
    slider: {
      min: 1,
      max: 5,
      lowLabel: 'Aceleye gelmem; dünya beklesin',
      highLabel: 'Bekleyemem; yürüyen merdivende de yürürüm',
    },
    shuffleOptions: false,
    followupPrompt:
      'Hanginiz kimi beklerken sabırsızlanırdı? Birlikte yavaşlamanız ya da hızlanmanız gereken bir an hayal edin.',
    qualityNote:
      '"Yürüyen merdivende de yürürüm" somut ve komik bir davranış imzası; soyut sıfat yerine görüntü verir.',
    status: 'active',
  },
  // Hayaller & Olasılıklar
  {
    slug: 'bir-gunluk-hayat',
    category: 'hayal',
    subcategory: 'hayat değişimi',
    trait: 'macera-istahi',
    level: 1,
    intensity: 2,
    type: 'choice',
    estSeconds: 15,
    sparkScore: 4,
    funScore: 5,
    prompt:
      'Bir günlüğüne bambaşka bir hayatı yaşayabilirsin; hafızan ve kimliğin sende kalıyor. Hangisini seçerdin?',
    options: [
      { id: 'sahne', label: 'Dünya turnesindeki bir grubun sahneye çıktığı gece' },
      { id: 'sahaf', label: 'Kıyı kasabasında küçük bir sahaf-kafenin sıradan salı günü' },
      { id: 'uzay', label: 'Uzay istasyonunda bir gün — evet, tuvaleti dahil' },
      { id: 'mutfak', label: 'Büyük bir mutfakta akşam servisinin tam ortası' },
    ],
    shuffleOptions: true,
    followupPrompt: 'Seçtiğiniz hayatın o gününde ilk yapacağınız şey ne olurdu?',
    qualityNote:
      'Düşük risk, yüksek hayal gücü; seçenekler adrenalin/huzur/merak/tutku eksenlerine dağılır. "Tuvaleti dahil" fanteziye gerçeklik göz kırpması.',
    status: 'active',
  },
  {
    slug: 'mutevazi-super-guc',
    category: 'hayal',
    subcategory: 'süper güç',
    trait: 'macera-istahi',
    level: 1,
    intensity: 1,
    type: 'either_or',
    estSeconds: 10,
    sparkScore: 5,
    funScore: 5,
    prompt: 'İki kusurlu süper güçten birini seçmek zorundasın. Hangisi?',
    options: [
      { id: 'ucus', label: 'Uçabilirsin — ama yürüme hızında' },
      { id: 'isinlanma', label: 'Işınlanabilirsin — ama sadece daha önce gittiğin bir yere' },
    ],
    shuffleOptions: true,
    followupPrompt:
      'Savunma turu: kendi gücünüzün neden açıkça daha iyi olduğuna birbirinizi ikna etmeye çalışın.',
    qualityNote:
      'Klişe süper güç sorusunun kusur eklenerek bükülmüş hâli: kusurlar seçimi gerçek bir tartıya çevirir, savunma turu garantidir.',
    status: 'active',
  },
  {
    slug: 'bir-yil-izin',
    category: 'hayal',
    subcategory: 'zaman hediyesi',
    trait: 'oncelik-pusulasi',
    level: 1,
    intensity: 2,
    type: 'choice',
    estSeconds: 15,
    sparkScore: 4,
    funScore: 4,
    prompt: 'Sana bir yıl izin verildi, geçim derdi yok. Ertesi sabah ilk hamlen ne olurdu?',
    options: [
      { id: 'bilet', label: 'Tek yön bilet; gerisini yolda çözerim' },
      { id: 'ogren', label: 'Hep ertelediğim o şeyi öğrenmeye yazılırım' },
      { id: 'sevdikler', label: 'Sevdiklerime uzun kahvaltılar borcum var; ödemeye başlarım' },
      { id: 'proje', label: 'Bir hafta dinlenirim, sonra dayanamayıp kendime bir proje açarım' },
    ],
    shuffleOptions: true,
    followupPrompt: 'O "hep ertelediğim şey" ne? İkiniz de birer tane itiraf edin.',
    qualityNote:
      'Önceliklerin hayal çerçevesinde güvenli ön izlemesi: kimse hayat planını savunmak zorunda kalmaz ama cevaplar çok şey anlatır.',
    status: 'active',
  },
  // Küçük İtiraflar
  {
    slug: 'gizli-keyif',
    category: 'itiraf',
    subcategory: 'suçlu zevkler',
    trait: 'kucuk-keyifler',
    level: 1,
    intensity: 1,
    type: 'choice',
    estSeconds: 12,
    sparkScore: 4,
    funScore: 5,
    prompt: 'Herkesin kimseye pek anlatmadığı küçük bir keyfi vardır. Seninki hangi bölgeden?',
    options: [
      { id: 'dizi', label: 'Yaşıma sorulmayacak diziler/filmler — ve hiç pişman değilim' },
      { id: 'sarki', label: 'Utanç verici derecede yapışkan şarkılar; listede gizli klasördeler' },
      { id: 'internet', label: 'İnternetin tuhaf köşeleri — buna araştırma diyelim' },
      { id: 'yemek', label: 'Aşırı spesifik bir yeme-içme tuhaflığı; sormayın, yaşıyorum' },
    ],
    shuffleOptions: true,
    followupPrompt:
      'Cesaret turu: gizli keyfinizden birer somut örnek verin. Gülmek serbest, yargı yasak.',
    qualityNote:
      'Karşılıklı küçük itiraf, hızlı yakınlık üreten en güvenli mekanizma; seçenekler kategori verir, teşhiri kullanıcıya bırakır.',
    status: 'active',
  },
  {
    slug: 'mesaj-itirafi',
    category: 'itiraf',
    subcategory: 'dijital alışkanlık',
    trait: 'temas-ritmi',
    level: 1,
    intensity: 1,
    type: 'either_or',
    estSeconds: 8,
    sparkScore: 4,
    funScore: 4,
    prompt: 'Dürüstlük anı: mesajlaşmada sen hangisisin?',
    options: [
      { id: 'sonra', label: '"Sonra cevaplarım" deyip üç gün sonra utançla dönen benim' },
      { id: 'aninda', label: 'Yazışma yarım kalamaz; okundu bilgim dürüsttür, cevabım anında' },
    ],
    shuffleOptions: true,
    followupPrompt:
      'Telefonunuzdaki en eski "cevaplanacaklar" mesajı ne kadar eski? Dürüstlük turu.',
    aiHint:
      'Bu bir arkadaşlık alışkanlığı itirafıdır; ilişki beklentisi yorumu yapma, geç cevabı kusur olarak çerçeveleme.',
    qualityNote:
      'Mesajlaşma beklentisini sormadan herkesin bildiği alışkanlığı itiraf çerçevesinde sorar; kusur komikleştirilerek güvenli kılındı.',
    status: 'active',
  },
  {
    slug: 'ev-konseri',
    category: 'itiraf',
    subcategory: 'yalnız hâller',
    trait: 'kucuk-keyifler',
    level: 1,
    intensity: 1,
    type: 'slider',
    estSeconds: 6,
    sparkScore: 3,
    funScore: 5,
    prompt: 'Evde yalnızsın ve müzik açtın. Sahne ne durumda?',
    slider: {
      min: 1,
      max: 5,
      lowLabel: 'Fonda çalar, ben işime bakarım',
      highLabel: 'Ev sahneye döner; süpürge mikrofon olabilir',
    },
    shuffleOptions: false,
    followupPrompt: 'Sizi en çok bu moda sokan şarkı hangisi? Birbirinize açın.',
    qualityNote:
      'Herkesin bildiği ama kimsenin sormadığı bir yalnızlık hâli; yüksek uç utanç değil coşku olarak yazıldı. Doğal kapanış sorusu.',
    status: 'active',
  },
  // Sosyal Dünya
  {
    slug: 'tatil-plancisi',
    category: 'sosyal',
    subcategory: 'grup rolü',
    trait: 'grup-rolu',
    level: 1,
    intensity: 1,
    type: 'choice',
    estSeconds: 12,
    sparkScore: 5,
    funScore: 4,
    prompt: 'Arkadaş grubun bir tatil planlıyor. Sen büyük ihtimalle hangisisin?',
    options: [
      { id: 'organizator', label: 'Tabloyu açan, uçuşları bulan, herkesi hizaya sokan organizatör' },
      { id: 'yolcu', label: '"Ben her şeye varım" diyen, planı taşımayan tatlı yolcu' },
      { id: 'revizyoncu', label: 'Son dakika "geliyorum ama şöyle olsa?" diyen revizyoncu' },
      { id: 'moral', label: 'Plana katkısı sıfır ama orada herkesi güldüren moral sorumlusu' },
    ],
    shuffleOptions: true,
    followupPrompt: 'Grup tatillerinden birer efsane anı: plan tutmadığında ne oldu?',
    qualityNote:
      'Kendini dışarıdan görme tipi grup sahnesiyle birleşir; dört rol de sevgiyle yazıldı, roller yan yana gelince espri kendiliğinden doğar.',
    status: 'active',
  },
  {
    slug: 'gece-sonrasi',
    category: 'sosyal',
    subcategory: 'sosyal enerji',
    trait: 'enerji-kaynagi',
    level: 1,
    intensity: 1,
    type: 'either_or',
    estSeconds: 8,
    sparkScore: 4,
    funScore: 3,
    prompt: 'Kalabalık, güzel bir geceden çıktın. Kapı kapandığı an içindeki his hangisi?',
    options: [
      { id: 'sarj', label: 'Şarj oldum — eve gelince de susamıyorum' },
      { id: 'pil-bitti', label: 'Harikaydı ama pilim bitti; şimdi sessizlik, güzel sessizlik' },
    ],
    shuffleOptions: true,
    followupPrompt: 'İkiniz için de mükemmel bir gece nasıl biter? Saatiyle, sahnesiyle anlatın.',
    aiHint:
      'İki seçenek de geceyi sevmiş durumda; içe dönüklüğü eksiklik gibi yorumlama.',
    qualityNote:
      'İçe/dışa dönüklüğü gece sonrası tek anla sorar; iki seçenek de "gece güzeldi" dediği için sosyal damga yapısal olarak imkânsız.',
    status: 'active',
  },
  // Ev Hâli
  {
    slug: 'kaos-sistemi',
    category: 'ev',
    subcategory: 'düzen',
    trait: 'duzen-kaos',
    level: 1,
    intensity: 1,
    type: 'slider',
    estSeconds: 6,
    sparkScore: 4,
    funScore: 4,
    prompt: 'Yaşam alanın hangi uca yakın?',
    slider: {
      min: 1,
      max: 5,
      lowLabel: 'Her şeyin bir yeri var ve oradadır',
      highLabel: 'Kaos gibi görünür ama içinde bir sistemim var',
    },
    shuffleOptions: false,
    followupPrompt:
      'Birbirinize "benim köşem" dediğiniz alanı tarif edin — kimsenin karışamayacağı bölge.',
    aiHint: 'Düzenli ucu daha olgun gösterme; iki uç da işleyen birer sistemdir.',
    qualityNote:
      'Rehberin slider kuralının birebir uygulaması: "düzenli ↔ dağınık" yargı ekseni "iki farklı sistem" eksenine çevrildi.',
    status: 'active',
  },
  {
    slug: 'evden-cikmama-gunu',
    category: 'ev',
    subcategory: 'ev günü',
    trait: 'ev-disari-dengesi',
    level: 1,
    intensity: 1,
    type: 'choice',
    estSeconds: 12,
    sparkScore: 3,
    funScore: 4,
    prompt: 'Bugünü resmen "evden çıkmama günü" ilan ettin. Evin en canlı köşesinde ne oluyor?',
    options: [
      { id: 'mutfak', label: 'Mutfak mesaisi: bir şeyler pişiyor, ev güzel kokuyor' },
      { id: 'koltuk', label: 'Koltuk + battaniye + "son bir bölüm" yalanı' },
      { id: 'hobi', label: 'Masaya yayılmış yarım projeler ve hobiler — bugün onların günü' },
      { id: 'balkon', label: 'Balkon/pencere kenarı: ben evdeyim ama gözüm dışarıda' },
    ],
    shuffleOptions: true,
    followupPrompt:
      'Evden çıkmama günlerinizi birleştirseniz o evde neler olurdu? Menüsüyle kurgulayın.',
    qualityNote:
      'Evin en canlı köşesini sorarak mekân üzerinden alışkanlık anlattırır; "son bir bölüm yalanı" öz-ironiyle herkesin hâlini meşrulaştırır.',
    status: 'active',
  },
]
