import type { QuestionContent } from '../types'

// Seviye 3 (Yakınlaşma) havuzu — 24 soru.
// Konu: iletişim tarzı, alan ihtiyacı, duygusal ifade, mesajlaşma beklentisi, yalnız zaman.
// Yasak bölge: üçüncü kişiler, kıyas.
// Parti kısıtları: kategori başına ≤3, trait başına ≤2,
// 8 ikilem / 10 çoktan seçmeli / 6 slider.
export const level3Questions: QuestionContent[] = [
  // İletişim & Duygular (L3 ana kategorisi)
  {
    slug: 'ozur-dili',
    category: 'iletisim',
    subcategory: 'özür biçimi',
    trait: 'ifade-tarzi',
    level: 3,
    intensity: 1,
    type: 'either_or',
    estSeconds: 8,
    sparkScore: 5,
    funScore: 4,
    prompt: 'Bir yakının kırıldığında, senin doğal özür dilin hangisi?',
    options: [
      { id: 'sozcuk', label: 'Sözcüklerle — ne hissettiğimi, neden üzgün olduğumu açıkça söylerim' },
      { id: 'eylem', label: 'Eylemle — konuşmak yerine bir şey yaparım, jest gösteririm' },
    ],
    shuffleOptions: true,
    followupPrompt:
      'Bir özrün sizi gerçekten rahatlatması için ne gerekir? Birbirinize anlatın.',
    aiHint: 'İki dil de samimi; sözcük dilini daha olgun gösterme.',
    qualityNote:
      'Özür biçimi iletişim derinliğini güvenli bir şekilde açar; iki seçenek de pozitif çerçevelenmiş.',
    answerWeights: {
      sozcuk: { 'ifade-tarzi': -1.5 },
      eylem: { 'ifade-tarzi': 1.5 },
    },
    status: 'active',
  },
  {
    slug: 'duygu-termometresi',
    category: 'iletisim',
    subcategory: 'duygusal ifade',
    trait: 'ifade-tarzi',
    level: 3,
    intensity: 2,
    type: 'slider',
    estSeconds: 6,
    sparkScore: 4,
    funScore: 3,
    prompt: 'Bir şey seni üzdüğünde çevrendekiler ne kadar fark eder?',
    slider: {
      min: 1,
      max: 5,
      lowLabel: 'Pek belli etmem; kendi içimde işlerim',
      highLabel: 'Yüzümden okunur; saklamayı beceremem zaten',
    },
    shuffleOptions: false,
    followupPrompt:
      'Birbirinizin "bir şeyler var" işaretlerini tahmin edin. Nelere bakarsınız?',
    aiHint: 'İki uç da bir iletişim biçimi; içe kapanmayı sorun olarak çerçeveleme.',
    qualityNote:
      'Duygusal ifade spektrumu L3 derinliği; iki uç da meşru kişilik olarak yazıldı.',
    answerWeights: {
      low: { 'ifade-tarzi': 1.5, 'alan-ihtiyaci': 0.5 },
      mid: {},
      high: { 'ifade-tarzi': -1.5 },
    },
    status: 'active',
  },
  {
    slug: 'destek-ihtiyaci',
    category: 'iletisim',
    subcategory: 'destek beklentisi',
    trait: 'alan-ihtiyaci',
    level: 3,
    intensity: 2,
    type: 'choice',
    estSeconds: 12,
    sparkScore: 5,
    funScore: 3,
    prompt: 'Kötü bir gün geçirdin. Sana en iyi gelen destek hangisi?',
    options: [
      { id: 'dinle', label: 'Sadece dinle, çözüm önerme — anlaşıldığımı hissetmek yeter' },
      { id: 'cozum', label: 'Birlikte çözüm düşünelim — harekete geçmek rahatlatır beni' },
      { id: 'alan', label: 'Beni rahat bırak — biraz kendi kendime toparlayınca gelirim' },
      { id: 'dikkat', label: 'Dikkatimi dağıt — konuşmadan güzel bir şey yapalım' },
    ],
    shuffleOptions: true,
    followupPrompt:
      'Bu dört yoldan hangisi en çok işinize yarar? Birbirinize "beni böyle destekle" rehberi verin.',
    aiHint: 'Dört ihtiyaç da sağlıklı; "alan isteme" yi kaçınma olarak yorumlama.',
    qualityNote:
      'Destek beklentisi L3 in en kritik sorularından; dört seçenek dört meşru ihtiyaç.',
    answerWeights: {
      dinle: { 'alan-ihtiyaci': -0.5, 'paylasim-istahi': 0.5 },
      cozum: { 'alan-ihtiyaci': -1 },
      alan: { 'alan-ihtiyaci': 1.5 },
      dikkat: { 'alan-ihtiyaci': 0.5 },
    },
    status: 'active',
  },
  // Sosyal Dünya (L3 derinlik)
  {
    slug: 'enerji-siniri',
    category: 'sosyal',
    subcategory: 'sosyal sınır',
    trait: 'alan-ihtiyaci',
    level: 3,
    intensity: 1,
    type: 'either_or',
    estSeconds: 8,
    sparkScore: 4,
    funScore: 4,
    prompt: 'Çok sevdiğin insanlarla bile "yeter, biraz yalnız kalmalıyım" anın olur mu?',
    options: [
      { id: 'olur', label: 'Kesinlikle — sevmekle sürekli birlikte olmak farklı şeyler' },
      { id: 'nadir', label: 'Pek olmaz; sevdiğim insanlar beni yormaz, aksine şarj eder' },
    ],
    shuffleOptions: true,
    followupPrompt:
      '"Yeter" sinyalinizi nasıl verirsiniz? Birbirinize ipuçlarınızı söyleyin.',
    qualityNote:
      'Alan ihtiyacını sevgi bağlamında sorar; iki cevap da pozitif.',
    answerWeights: {
      olur: { 'alan-ihtiyaci': 1.5, 'enerji-kaynagi': 1 },
      nadir: { 'alan-ihtiyaci': -1, 'enerji-kaynagi': -1 },
    },
    status: 'active',
  },
  {
    slug: 'kiskanclik-termometresi',
    category: 'sosyal',
    subcategory: 'kıskançlık eşiği',
    trait: 'temas-ritmi',
    level: 3,
    intensity: 2,
    type: 'slider',
    estSeconds: 6,
    sparkScore: 4,
    funScore: 3,
    prompt: 'Yakın ilişkilerinde kıskançlık eşiğin nerede?',
    slider: {
      min: 1,
      max: 5,
      lowLabel: 'Çok rahatım; güvendiğim kişi istediği yere gider',
      highLabel: 'Biraz sahiplenici olabilirim; önemsemek böyle bir şey',
    },
    shuffleOptions: false,
    followupPrompt:
      'Kıskançlık hissettiren bir an yaşadınız mı? Ne yaptınız?',
    aiHint: 'İki uç da sahiplenilebilir; sahipleniciyi olumsuz, rahatı kayıtsız gösterme.',
    qualityNote:
      'Kıskançlığı hafif çerçevede, spektrum olarak sorar. L3 derinliği ama güvenli.',
    answerWeights: {
      low: { 'temas-ritmi': 1, 'bagimsizlik-dengesi': 1 },
      mid: {},
      high: { 'temas-ritmi': -1 },
    },
    status: 'active',
  },
  {
    slug: 'cevapsiz-mesaj',
    category: 'sosyal',
    subcategory: 'iletişim beklentisi',
    trait: 'temas-ritmi',
    level: 3,
    intensity: 2,
    type: 'choice',
    estSeconds: 12,
    sparkScore: 5,
    funScore: 4,
    prompt: 'Önemsediğin biri mesajına saatlerdir cevap vermedi. Kafandan ne geçer?',
    options: [
      { id: 'mesgul', label: 'Meşguldür — herkesin kendi hayatı var, döner bir yerden' },
      { id: 'merak', label: 'Bir şey mi oldu acaba? Hafif bir merak başlar' },
      { id: 'tedirgin', label: 'Acaba bir şey mi yaptım? Kafamda senaryolar döner' },
      { id: 'tekrar', label: 'Bir mesaj daha atarım; belki görmemiştir' },
    ],
    shuffleOptions: true,
    followupPrompt:
      'Mesaj beklentinizi açıkça konuşun: ne kadar sürede cevap bekliyorsunuz?',
    aiHint: 'Dört tepki de insani; tedirginliği güvensizlik olarak etiketleme.',
    qualityNote:
      'Mesajlaşma beklentisini senaryo ile sorar; L3 derinliğinde iletişim ritmi.',
    answerWeights: {
      mesgul: { 'temas-ritmi': 1, 'guven-inshasi': -0.5 },
      merak: { 'temas-ritmi': -0.5 },
      tedirgin: { 'temas-ritmi': -1 },
      tekrar: { 'temas-ritmi': -1.5 },
    },
    status: 'active',
  },
  // Ev Hâli (L3 derinlik)
  {
    slug: 'birlikte-sessizlik',
    category: 'ev',
    subcategory: 'birlikte vakit',
    trait: 'enerji-kaynagi',
    level: 3,
    intensity: 1,
    type: 'either_or',
    estSeconds: 8,
    sparkScore: 4,
    funScore: 4,
    prompt: 'Sevdiğin biriyle aynı evdesin, ikiniz de ayrı şeylerle meşgul, sessizlik var. Bu an senin için ne?',
    options: [
      { id: 'ideal', label: 'Tam da bu — aynı yerde olmak yeter, sürekli konuşmak gerekmez' },
      { id: 'eksik', label: 'Bir şeyler yapalım istiyorum; yan yana ama ayrı olmak bana az gelir' },
    ],
    shuffleOptions: true,
    followupPrompt:
      'Birlikte sessizlik sizin için ne ifade ediyor? Aynı şeyi mi hissediyorsunuz?',
    qualityNote:
      'Birlikte sessizlik sorusu ilişki alışkanlıklarının en temel kontrast noktalarından; L3 güvenli derinlik.',
    answerWeights: {
      ideal: { 'enerji-kaynagi': 1, 'alan-ihtiyaci': 0.5 },
      eksik: { 'enerji-kaynagi': -1.5, 'paylasim-istahi': 0.5 },
    },
    status: 'active',
  },
  {
    slug: 'ev-kural-catismasi',
    category: 'ev',
    subcategory: 'çatışma çözümü',
    trait: 'tartisma-tarzi',
    level: 3,
    intensity: 2,
    type: 'choice',
    estSeconds: 12,
    sparkScore: 4,
    funScore: 3,
    prompt: 'Birlikte yaşadığın biriyle ufak bir ev meselesi üzerine ters düştünüz. Doğal refleksin?',
    options: [
      { id: 'hemen', label: 'O an konuşurum — küçük şeyler birikmeden çözülmeli' },
      { id: 'yaz', label: 'Not alır, uygun bir anda derli toplu anlatırım' },
      { id: 'uyum', label: 'Çoğu şeyde uyum sağlarım; kavga etmeye değmez' },
      { id: 'espri', label: 'Espriyle açarım; gerginliği düşürüp öyle konuşuruz' },
    ],
    shuffleOptions: true,
    followupPrompt:
      'Ev içi anlaşmazlıklarda "benim kırmızı çizgim" dediğiniz konu ne?',
    aiHint: 'Dört stil de olgun olabilir; uyum sağlamayı pasiflik olarak çerçeveleme.',
    qualityNote:
      'Ev çatışması L3 te güvenli bir iletişim derinliği; günlük hayat sahnesiyle somutlaştırılmış.',
    answerWeights: {
      hemen: { 'tartisma-tarzi': -1.5 },
      yaz: { 'tartisma-tarzi': 0.5, 'ifade-tarzi': 1 },
      uyum: { 'tartisma-tarzi': 1.5 },
      espri: { 'tartisma-tarzi': 0.5, 'mizah-tarzi': 1 },
    },
    status: 'active',
  },
  {
    slug: 'yalniz-zaman-ihtiyaci',
    category: 'ev',
    subcategory: 'kişisel zaman',
    trait: 'enerji-kaynagi',
    level: 3,
    intensity: 2,
    type: 'slider',
    estSeconds: 6,
    sparkScore: 4,
    funScore: 3,
    prompt: 'Haftada ne kadar "tamamen yalnız" zamana ihtiyaç duyarsın?',
    slider: {
      min: 1,
      max: 5,
      lowLabel: 'Pek duymam; birisi varsa daha iyi',
      highLabel: 'Düzenli yalnız zamanım olmazsa performansım düşer',
    },
    shuffleOptions: false,
    followupPrompt:
      'Yalnız zamanınızda ne yaparsınız? Birbirinize "dokunulmaz saatinizi" anlatın.',
    qualityNote:
      'Yalnız zaman ihtiyacı L3 derinliği; spektrum iki ucu da pozitif çerçeveler.',
    answerWeights: {
      low: { 'enerji-kaynagi': -1.5 },
      mid: {},
      high: { 'enerji-kaynagi': 1.5, 'alan-ihtiyaci': 1 },
    },
    status: 'active',
  },
  // Günlük Ritim (L3 derinlik)
  {
    slug: 'stres-sinyali',
    category: 'ritim',
    subcategory: 'stres yönetimi',
    trait: 'konfor-alani',
    level: 3,
    intensity: 1,
    type: 'choice',
    estSeconds: 12,
    sparkScore: 4,
    funScore: 4,
    prompt: 'Stresli bir dönemde çevrendekiler senden ilk neyi fark eder?',
    options: [
      { id: 'sessiz', label: 'Sessizleşirim — konuşmam azalır, kendi kabuğuma çekilirim' },
      { id: 'hizli', label: 'Hızlanırım — çok iş yapar, çok hareket eder, duramam' },
      { id: 'gergin', label: 'Sabırsızlaşırım — küçük şeylere bile tepki veririm' },
      { id: 'kontrol', label: 'Her şeyi kontrol etmeye çalışırım — listeler, planlar, düzen' },
    ],
    shuffleOptions: true,
    followupPrompt:
      'Birbirinizin stres sinyallerini öğrenin: "beni böyle görürsen, o gün zor geçiyor demektir."',
    qualityNote:
      'Stres sinyali L3 te kendini tanıma derinliği; dört sinyal de insani ve yargısız.',
    answerWeights: {
      sessiz: { 'konfor-alani': 1, 'alan-ihtiyaci': 1 },
      hizli: { 'tempo': 1 },
      gergin: { 'konfor-alani': -0.5 },
      kontrol: { 'plan-sevgisi': 1 },
    },
    status: 'active',
  },
  {
    slug: 'karar-verme-hizi',
    category: 'ritim',
    subcategory: 'karar mekanizması',
    trait: 'tempo',
    level: 3,
    intensity: 2,
    type: 'either_or',
    estSeconds: 8,
    sparkScore: 4,
    funScore: 4,
    prompt: 'Önemli bir karar vereceksin. Sen hangisisin?',
    options: [
      { id: 'hizli', label: 'İçgüdüme güvenirim; düşündükçe kafam karışır, hızlı karar iyidir' },
      { id: 'yavas', label: 'Her açıdan tartarım; acele karar pişmanlık getirir' },
    ],
    shuffleOptions: true,
    followupPrompt:
      'En zor kararınız ne oldu? Nasıl verdiniz, pişman oldunuz mu?',
    qualityNote:
      'Karar verme hızı L3 derinliğinde tempo ve risk iştahını birlikte yoklar.',
    answerWeights: {
      hizli: { 'tempo': 1, 'risk-istahi': 0.5 },
      yavas: { 'tempo': -1, 'plan-sevgisi': 0.5 },
    },
    status: 'active',
  },
  {
    slug: 'degisim-refleksi',
    category: 'ritim',
    subcategory: 'değişime uyum',
    trait: 'konfor-alani',
    level: 3,
    intensity: 2,
    type: 'slider',
    estSeconds: 6,
    sparkScore: 3,
    funScore: 3,
    prompt: 'Hayatında beklenmedik bir değişiklik olduğunda ilk tepkin nereye düşer?',
    slider: {
      min: 1,
      max: 5,
      lowLabel: 'Tedirginlik — bildik düzenim bozulmasın',
      highLabel: 'Heyecan — değişiklik yeni kapılar açar',
    },
    shuffleOptions: false,
    followupPrompt:
      'Hayatınızı en çok değiştiren beklenmedik olay ne oldu? İyi mi bitti?',
    qualityNote:
      'Değişime uyum L3 derinliğinde psikolojik esnekliği yoklar.',
    answerWeights: {
      low: { 'konfor-alani': 1.5 },
      mid: {},
      high: { 'konfor-alani': -1.5, 'risk-istahi': 0.5 },
    },
    status: 'active',
  },
  // Para Alışkanlıkları (L3 derinlik)
  {
    slug: 'para-konusmak',
    category: 'para',
    subcategory: 'para iletişimi',
    trait: 'para-keyif-dengesi',
    level: 3,
    intensity: 2,
    type: 'either_or',
    estSeconds: 8,
    sparkScore: 5,
    funScore: 3,
    prompt: 'Yakın biriyle para konusunu açmak senin için nasıl?',
    options: [
      { id: 'rahat', label: 'Rahat — para da hayatın bir parçası, konuşulur' },
      { id: 'zor', label: 'Biraz zor — para konuşmak beni hep tedirgin eder' },
    ],
    shuffleOptions: true,
    followupPrompt:
      'Para konusunda birbirinize sormaktan çekindiğiniz bir soru var mı?',
    aiHint: 'İki tutum da anlaşılabilir; para konuşmaktan kaçınmayı olgunluk eksikliği olarak çerçeveleme.',
    qualityNote:
      'Para iletişimi L3 derinliğinde; basit ikilem ama çok şey anlatan bir soru.',
    answerWeights: {
      rahat: { 'para-keyif-dengesi': -0.5, 'ifade-tarzi': -0.5 },
      zor: { 'para-keyif-dengesi': 0.5, 'ifade-tarzi': 1 },
    },
    status: 'active',
  },
  {
    slug: 'guvenlik-hissi',
    category: 'para',
    subcategory: 'finansal güvenlik',
    trait: 'risk-istahi',
    level: 3,
    intensity: 2,
    type: 'choice',
    estSeconds: 12,
    sparkScore: 4,
    funScore: 3,
    prompt: 'Finansal güvenlik hissi senin için nereden gelir?',
    options: [
      { id: 'birikim', label: 'Kenarda yeterli birikim — beklenmedik durumlar için hazır olmak' },
      { id: 'gelir', label: 'Düzenli gelir — gelen bildikçe rahatım, birikime takılmam' },
      { id: 'yetenek', label: 'Kendime güven — ne olursa olsun bir şekilde çözerim' },
      { id: 'az', label: 'Az ihtiyaçla yaşamak — harcamam azsa endişem de az' },
    ],
    shuffleOptions: true,
    followupPrompt:
      'Finansal olarak en rahat hissettiğiniz dönem hangisiydi? Neden?',
    qualityNote:
      'Güvenlik hissi L3 te değer derinliği; dört kaynak da meşru ve kişilik yansıtır.',
    answerWeights: {
      birikim: { 'risk-istahi': -1.5, 'plan-sevgisi': 0.5 },
      gelir: { 'risk-istahi': -0.5 },
      yetenek: { 'risk-istahi': 1.5 },
      az: { 'risk-istahi': 0.5, 'konfor-alani': 0.5 },
    },
    status: 'active',
  },
  {
    slug: 'hediye-dili',
    category: 'para',
    subcategory: 'hediye alışkanlığı',
    trait: 'paylasim-istahi',
    level: 3,
    intensity: 1,
    type: 'choice',
    estSeconds: 12,
    sparkScore: 4,
    funScore: 5,
    prompt: 'Birine hediye alırken sen hangisisin?',
    options: [
      { id: 'ararken', label: 'Haftalarca araştırır, mükemmeli bulana kadar almam' },
      { id: 'spontan', label: 'Gördüm, hatırladım, aldım — plansız hediye en iyisi' },
      { id: 'pratik', label: 'İşe yarar bir şey alırım; sembolik hediye bana anlamsız gelir' },
      { id: 'deneyim', label: 'Eşya almam; birlikte bir şey yapmaya davet ederim' },
    ],
    shuffleOptions: true,
    followupPrompt:
      'Aldığınız veya aldığınız en unutulmaz hediye ne? Birbirinize anlatın.',
    qualityNote:
      'Hediye alışkanlığı L3 te sevgi dili ve para kesişimi; dört stil de pozitif.',
    answerWeights: {
      ararken: { 'paylasim-istahi': 1, 'plan-sevgisi': 0.5 },
      spontan: { 'paylasim-istahi': 1, 'spontanlik': 1 },
      pratik: { 'paylasim-istahi': -0.5 },
      deneyim: { 'paylasim-istahi': 0.5, 'macera-istahi': 0.5 },
    },
    status: 'active',
  },
  // Seyahat & Keşif (L3)
  {
    slug: 'uzun-yol-testi',
    category: 'kesif',
    subcategory: 'seyahat uyumu',
    trait: 'sabah-gece-ritmi',
    level: 3,
    intensity: 1,
    type: 'either_or',
    estSeconds: 8,
    sparkScore: 4,
    funScore: 5,
    prompt: 'Uzun bir yolculukta araç kullanan sensin. Yanındaki uyuya kaldı. Tepkin?',
    options: [
      { id: 'normal', label: 'Uyusun, müziğim var — yalnız sürmek de keyifli' },
      { id: 'durt', label: 'Hafifçe dürtürüm — yolculuğun güzelliği sohbetteydi' },
    ],
    shuffleOptions: true,
    followupPrompt:
      'Uzun yolculuklarda en iyi anınız ne oldu? Yol hikâyesi turu.',
    qualityNote:
      'Seyahat uyumu L3 te birlikte vakit geçirme stilini yolculuk sahnesinde yoklar.',
    answerWeights: {
      normal: { 'alan-ihtiyaci': 0.5, 'sabah-gece-ritmi': -0.5 },
      durt: { 'paylasim-istahi': 0.5, 'enerji-kaynagi': -0.5 },
    },
    status: 'active',
  },
  {
    slug: 'farkli-tatil-beklentisi',
    category: 'kesif',
    subcategory: 'beklenti yönetimi',
    trait: 'tartisma-tarzi',
    level: 3,
    intensity: 2,
    type: 'choice',
    estSeconds: 12,
    sparkScore: 5,
    funScore: 4,
    prompt: 'Birlikte tatile çıktınız ama beklentileriniz çok farklı çıktı. Sen ne yaparsın?',
    options: [
      { id: 'uyum', label: 'Uyum sağlarım — tatil kavga edilecek yer değil' },
      { id: 'ortayol', label: 'Orta yol ararım — bir gün senin planın, bir gün benim' },
      { id: 'konusma', label: 'Açıkça konuşurum — beklentileri paylaşmadan çözüm olmaz' },
      { id: 'ayril', label: 'Birkaç saat ayrı takılırız — herkes kendi keyfine baksın, akşam buluşuruz' },
    ],
    shuffleOptions: true,
    followupPrompt:
      'Tatilde beklenti çatışması yaşadınız mı? Nasıl çözdünüz?',
    qualityNote:
      'Tatil çatışması L3 derinliğinde ilişki içi beklenti yönetimini somut sahneyle sorar.',
    answerWeights: {
      uyum: { 'tartisma-tarzi': 1.5 },
      ortayol: { 'tartisma-tarzi': 0.5 },
      konusma: { 'tartisma-tarzi': -1.5, 'ifade-tarzi': -0.5 },
      ayril: { 'alan-ihtiyaci': 1, 'bagimsizlik-dengesi': 1 },
    },
    status: 'active',
  },
  // Tat & Mutfak (L3)
  {
    slug: 'yemek-tartismasi',
    category: 'lezzet',
    subcategory: 'yemek kararı',
    trait: 'tempo',
    level: 3,
    intensity: 1,
    type: 'either_or',
    estSeconds: 8,
    sparkScore: 4,
    funScore: 5,
    prompt: '"Bu akşam ne yiyelim?" sorusunda sen hangisisin?',
    options: [
      { id: 'onerici', label: 'Hemen üç seçenek sunarım — birisi seçsin, konu kapansın' },
      { id: 'fark-etmez', label: '"Fark etmez, sen seç" derim — sonra önerilenlerin yarısını reddederim' },
    ],
    shuffleOptions: true,
    followupPrompt:
      '"Ne yiyelim" tartışmasının en uzun sürdüğü anınız? Sonunda ne yediniz?',
    qualityNote:
      'Evrensel bir günlük mini çatışmayı espriyle yoklar; L3 iletişim derinliğinin hafif versiyonu.',
    answerWeights: {
      onerici: { 'tempo': 1, 'grup-rolu': -1 },
      'fark-etmez': { 'tempo': -0.5 },
    },
    status: 'active',
  },
  {
    slug: 'mutfak-paylasimi',
    category: 'lezzet',
    subcategory: 'birlikte pişirme',
    trait: 'grup-rolu',
    level: 3,
    intensity: 2,
    type: 'choice',
    estSeconds: 12,
    sparkScore: 4,
    funScore: 4,
    prompt: 'Biriyle birlikte yemek yapıyorsunuz. Mutfaktaki doğal rolün hangisi?',
    options: [
      { id: 'sef', label: 'Şef — tarifi ben yönetirim, sen doğra' },
      { id: 'yardimci', label: 'Mutlu yardımcı — söyle ne yapayım, orada olayım yeter' },
      { id: 'kendi', label: 'Herkes kendi alanında — sen salatanı yap, ben sosumu yapayım' },
      { id: 'sohbet', label: 'Ben tezgâhta oturup sohbet ederim; moral desteği de destektir' },
    ],
    shuffleOptions: true,
    followupPrompt:
      'Birlikte bir yemek yapın! Ne pişireceksiniz, rolleri şimdiden bölün.',
    qualityNote:
      'Birlikte pişirme sahnesi L3 te paylaşım ve kontrol dinamiğini yoklar.',
    answerWeights: {
      sef: { 'grup-rolu': -1.5 },
      yardimci: { 'grup-rolu': 1 },
      kendi: { 'alan-ihtiyaci': 0.5, 'bagimsizlik-dengesi': 0.5 },
      sohbet: { 'grup-rolu': 1.5, 'paylasim-istahi': 0.5 },
    },
    status: 'active',
  },
  // Kültür & Eğlence (L3)
  {
    slug: 'spoiler-politikasi',
    category: 'kultur',
    subcategory: 'paylaşım alışkanlığı',
    trait: 'paylasim-istahi',
    level: 3,
    intensity: 1,
    type: 'either_or',
    estSeconds: 8,
    sparkScore: 3,
    funScore: 5,
    prompt: 'Harika bir dizi/film izledin. Karşındaki henüz izlememiş. Ne yaparsın?',
    options: [
      { id: 'dikkatli', label: 'Ağzımı sıkı tutarım — spoiler vermek suçtur' },
      { id: 'heyecan', label: 'Dayanamam; "bir şey söylemeyeceğim ama..." diye başlarım' },
    ],
    shuffleOptions: true,
    followupPrompt:
      'En büyük spoiler facianızı anlatın: kim verdi, ne oldu?',
    qualityNote:
      'Spoiler politikası evrensel ve güldüren bir alışkanlık; L3 te iletişim tarzını hafif bir kapıdan açar.',
    answerWeights: {
      dikkatli: { 'paylasim-istahi': -1 },
      heyecan: { 'paylasim-istahi': 1.5 },
    },
    status: 'active',
  },
  {
    slug: 'birlikte-izleme-kurali',
    category: 'kultur',
    subcategory: 'birlikte deneyim',
    trait: 'grup-rolu',
    level: 3,
    intensity: 2,
    type: 'choice',
    estSeconds: 12,
    sparkScore: 4,
    funScore: 4,
    prompt: 'Birlikte bir dizi izliyorsunuz. Karşındaki bir bölüm öne geçti. Tepkin?',
    options: [
      { id: 'ihanet', label: 'İhanet! Birlikte başladık, birlikte biter' },
      { id: 'anlayis', label: 'Anlayışla karşılarım, ama spoiler verirse... o ayrı' },
      { id: 'katilir', label: 'Ben de öne geçerim; artık herkes kendi hızında' },
    ],
    shuffleOptions: true,
    followupPrompt:
      'Birlikte izleme kuralınız ne olurdu? Bir "dizi anayasası" yazın.',
    qualityNote:
      'Birlikte izleme kuralı L3 te paylaşım ve beklenti yönetimini popüler kültür üzerinden sorar.',
    answerWeights: {
      ihanet: { 'paylasim-istahi': 1, 'grup-rolu': -0.5 },
      anlayis: { 'paylasim-istahi': 0.5 },
      katilir: { 'bagimsizlik-dengesi': 1 },
    },
    status: 'active',
  },
  // Hayaller & Olasılıklar (L3)
  {
    slug: 'ileri-geri',
    category: 'hayal',
    subcategory: 'zaman tercihi',
    trait: 'nostalji-bagi',
    level: 3,
    intensity: 2,
    type: 'either_or',
    estSeconds: 10,
    sparkScore: 5,
    funScore: 4,
    prompt: 'Geçmişte bir anı yeniden yaşamak mı, gelecekte bir günü şimdiden görmek mi?',
    options: [
      { id: 'gecmis', label: 'Geçmişe — o anı bir kere daha hissetmek isterim' },
      { id: 'gelecek', label: 'Geleceğe — merak öldürür; bir bakış yeter' },
    ],
    shuffleOptions: true,
    followupPrompt:
      'Hangi anı tekrar yaşardınız veya hangi günü görmek isterdiniz? Detaylarıyla anlatın.',
    qualityNote:
      'Zaman tercihi L3 derinliğinde nostalji bağı ve gelecek merakını yoklar; kişisel hikâye tetikler.',
    answerWeights: {
      gecmis: { 'nostalji-bagi': 1.5 },
      gelecek: { 'nostalji-bagi': -1.5, 'risk-istahi': 0.5 },
    },
    status: 'active',
  },
  // Hayaller & Olasılıklar (L3) — ikinci soru
  {
    slug: 'zihin-okuma',
    category: 'hayal',
    subcategory: 'empati derinliği',
    trait: 'risk-istahi',
    level: 3,
    intensity: 2,
    type: 'slider',
    estSeconds: 6,
    sparkScore: 5,
    funScore: 4,
    prompt: 'Bir günlüğüne zihin okuyabilsen — ama karşındaki de seninkini okuyabilse — ister misin?',
    slider: {
      min: 1,
      max: 5,
      lowLabel: 'Hayır — bazı düşünceler kişiye özel kalmalı',
      highLabel: 'Evet — tam şeffaflık özgürleştirici olurdu',
    },
    shuffleOptions: false,
    followupPrompt:
      'Birbirinizin hangi düşüncesini merak ediyorsunuz? Şimdi sorun!',
    qualityNote:
      'Zihin okuma sorusu L3 te empati ve şeffaflık ihtiyacını hipotetik sahneyle yoklar.',
    answerWeights: {
      low: { 'alan-ihtiyaci': 1.5, 'risk-istahi': -0.5 },
      mid: {},
      high: { 'ifade-tarzi': -1, 'risk-istahi': 1 },
    },
    status: 'active',
  },
  // Nostalji (L3)
  {
    slug: 'eski-arkadas',
    category: 'nostalji',
    subcategory: 'arkadaşlık geçmişi',
    trait: 'nostalji-bagi',
    level: 3,
    intensity: 2,
    type: 'choice',
    estSeconds: 15,
    sparkScore: 4,
    funScore: 3,
    prompt: 'Yıllar önce çok yakın olduğun ama artık görüşmediğin biri var. Bu durum seni nasıl etkiler?',
    options: [
      { id: 'huzun', label: 'Hafif bir hüzün — keşke devam etseydi ama hayat öyle' },
      { id: 'kabul', label: 'İnsanlar gelir gider; her dönemin insanları farklı, bu doğal' },
      { id: 'arama', label: 'Arada aklıma gelir, bir gün aramayı düşünürüm — ama hiç aramam' },
      { id: 'kapali', label: 'O sayfa kapandı; geriye bakmam, ileri yürürüm' },
    ],
    shuffleOptions: true,
    followupPrompt:
      'Özlediğiniz ama aramadığınız biri var mı? Neden aramadınız?',
    aiHint: 'Dört tepki de insani ve meşru; "kapali" seçeneğini soğukluk olarak çerçeveleme.',
    qualityNote:
      'Eski arkadaşlık L3 derinliğinde bağlanma ve kaybetme tarzını güvenli çerçevede yoklar.',
    answerWeights: {
      huzun: { 'nostalji-bagi': 1.5, 'paylasim-istahi': 0.5 },
      kabul: { 'nostalji-bagi': 0.5 },
      arama: { 'nostalji-bagi': 1 },
      kapali: { 'nostalji-bagi': -1.5 },
    },
    status: 'active',
  },
]
